/* GENERATED by gen_full_c.py -- do not edit. */
#ifndef NN_AOT_META_H
#define NN_AOT_META_H

#define AOT_N_OUT      7
#define AOT_N_PORTS    5
#define AOT_LOGICAL_PORTS { 0, 1, 2, 3, 4 }

/* class 0: FORWARD -> logical_port 0 */
/* class 1: FORWARD -> logical_port 1 */
/* class 2: FORWARD -> logical_port 2 */
/* class 3: FORWARD -> logical_port 3 */
/* class 4: FORWARD -> logical_port 4 */
/* class 5: DROP */
/* class 6: UNUSED */

#endif
