import torch
import json
import os
import sys

from FRR_model import FastRerouteMLP

print("Extracting weights from PyTorch model...")

model = FastRerouteMLP(n_interfaces=6, n_nodes=52, hidden_dim=4)
model.load_state_dict(torch.load("frr_germany50_5_model_4x2.pt"))

# ---------------------------------------------------------------------------
# Method 1 - PTQ: SCALE_FACTOR computed automatically from the maximum weight.
#
# SCALE_FACTOR = floor(127 / max(|w|))
# Ensures no weight exceeds int8 range [-128, 127] after multiplication,
# eliminating clamping that would cause TABLE MISS.
#
# The SCALE_FACTOR is saved in weights_float.json along with the original
# float weights, and is written into the IPA header 'scaling' field by send_ipa.
# The kernel reads it from the header and uses it as a divisor (instead of shift).
# ---------------------------------------------------------------------------

all_floats = [w for param in model.parameters() for w in param.data.view(-1).tolist()]
max_abs    = max(abs(w) for w in all_floats)
SCALE_FACTOR = int(127 / max_abs)

print(f"Max |weight| = {max_abs:.6f}")
print(f"SCALE_FACTOR = floor(127 / {max_abs:.6f}) = {SCALE_FACTOR}")

integer_weights = []
for w_float in all_floats:
    w_int = int(round(w_float * SCALE_FACTOR))
    w_int = max(-128, min(127, w_int))  # safety clamp (should not trigger)
    integer_weights.append(w_int)

# Verify that no weight was clamped
clamped = sum(1 for w, wf in zip(integer_weights, all_floats)
              if w != int(round(wf * SCALE_FACTOR)))
if clamped:
    print(f"[WARN] {clamped} weights clamped (max_abs may not be the true maximum)")
else:
    print("No weights were clamped. int8 range respected for all weights.")

# int8 weights -> eBPF kernel
with open("weights.json", "w") as f:
    json.dump(integer_weights, f)

# original float weights + SCALE_FACTOR -> control plane for Method 1
with open("weights_float.json", "w") as f:
    json.dump({"scale_factor": SCALE_FACTOR, "weights": all_floats}, f)

print(f"Saved {len(integer_weights)} int8 weights -> weights.json")
print(f"Saved float weights + scale_factor={SCALE_FACTOR} -> weights_float.json")
print(f"int8 range: min={min(integer_weights)}  max={max(integer_weights)}")


# ===========================================================================
# C EMIT — hardcoded model weight arrays
# ===========================================================================

def _fmt_row(values, indent=4):
    """Format a list of ints as a C array row: {  v0,  v1, ... }"""
    inner = ", ".join(f"{v:4d}" for v in values)
    return " " * indent + "{ " + inner + " }"


def emit_c_hardcoded(model, scale_factor, model_id, out_dir="."):
    """
    Generate the C weight arrays for a hardcoded eBPF model program.

    Reads all named parameters from `model` (must follow the FastRerouteMLP
    convention: fc1.weight, fc1.bias, fc2.weight, fc2.bias).
    Quantises each parameter with `scale_factor` (INT8, clamped to [-128,127]).
    Writes the result to `out_dir/model_<model_id>_weights.h`.

    The generated header is meant to be #included in the corresponding
    src/hardcoded/ebpf/model_<id>.c, replacing the placeholder arrays.

    Parameters
    ----------
    model        : nn.Module  — the loaded PyTorch model
    scale_factor : int        — PTQ scale factor (same as SCALE_FACTOR above)
    model_id     : int        — numeric ID used in the filename and comments
    out_dir      : str        — output directory (default: current directory)

    Returns
    -------
    str  — path to the generated header file
    """
    params = dict(model.named_parameters())

    def _quant(tensor):
        vals = tensor.data.view(-1).tolist()
        return [max(-128, min(127, int(round(v * scale_factor)))) for v in vals]

    def _quant_bias(tensor):
        # Biases are scaled by scale_factor^2 in the INT8 accumulator:
        # out = W8 * x8 + b8 * S^2  →  b8 = round(b_float * S)
        # We use the same S here; the model_<id>.c multiplies b by SCALE^2.
        vals = tensor.data.view(-1).tolist()
        return [max(-128, min(127, int(round(v * scale_factor)))) for v in vals]

    # ---- Layer 1 ----
    w1_raw  = params["fc1.weight"]          # [hidden, n_features]
    b1_raw  = params["fc1.bias"]            # [hidden]
    hidden  = w1_raw.shape[0]
    n_feat  = w1_raw.shape[1]
    w1_int  = _quant(w1_raw)
    b1_int  = _quant_bias(b1_raw)

    # ---- Layer 2 ----
    w2_raw  = params["fc2.weight"]          # [n_classes, hidden]
    b2_raw  = params["fc2.bias"]            # [n_classes]
    n_cls   = w2_raw.shape[0]
    w2_int  = _quant(w2_raw)
    b2_int  = _quant_bias(b2_raw)

    # ---- Build C source ----
    lines = [
        f"/* AUTO-GENERATED by shared/extract_weights.py — DO NOT EDIT */",
        f"/* Model ID : {model_id} */",
        f"/* Scale    : {scale_factor} (INT8 PTQ) */",
        f"/* Architecture: {n_feat} -> {hidden} -> {n_cls} */",
        "",
        f"#ifndef MODEL_{model_id}_WEIGHTS_H",
        f"#define MODEL_{model_id}_WEIGHTS_H",
        "",
        f"#define N_FEATURES  {n_feat}",
        f"#define HIDDEN_SIZE {hidden}",
        f"#define N_CLASSES   {n_cls}",
        f"#define SCALE       {scale_factor}",
        "",
    ]

    # W1[HIDDEN_SIZE][N_FEATURES]
    lines.append(f"static const int W1[HIDDEN_SIZE][N_FEATURES] = {{")
    for row_idx in range(hidden):
        row = w1_int[row_idx * n_feat : (row_idx + 1) * n_feat]
        comma = "," if row_idx < hidden - 1 else ""
        lines.append(_fmt_row(row) + comma)
    lines.append("};")
    lines.append("")

    # b1[HIDDEN_SIZE]
    b1_str = ", ".join(f"{v:4d}" for v in b1_int)
    lines.append(f"static const int b1[HIDDEN_SIZE] = {{ {b1_str} }};")
    lines.append("")

    # W2[N_CLASSES][HIDDEN_SIZE]
    lines.append(f"static const int W2[N_CLASSES][HIDDEN_SIZE] = {{")
    for row_idx in range(n_cls):
        row = w2_int[row_idx * hidden : (row_idx + 1) * hidden]
        comma = "," if row_idx < n_cls - 1 else ""
        lines.append(_fmt_row(row) + comma)
    lines.append("};")
    lines.append("")

    # b2[N_CLASSES]
    b2_str = ", ".join(f"{v:4d}" for v in b2_int)
    lines.append(f"static const int b2[N_CLASSES] = {{ {b2_str} }};")
    lines.append("")
    lines.append(f"#endif /* MODEL_{model_id}_WEIGHTS_H */")
    lines.append("")

    out_path = os.path.join(out_dir, f"model_{model_id}_weights.h")
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))

    print(f"[emit_c] Written {out_path}")
    print(f"  Architecture : {n_feat} -> {hidden} -> {n_cls}")
    print(f"  Scale factor : {scale_factor}")
    print(f"  W1 range     : [{min(w1_int)}, {max(w1_int)}]")
    print(f"  W2 range     : [{min(w2_int)}, {max(w2_int)}]")

    # Sanity: count any values that hit the ±128/127 boundary
    clipped = sum(1 for v in w1_int + w2_int + b1_int + b2_int if abs(v) >= 127)
    if clipped:
        print(f"  [WARN] {clipped} weight(s) at ±127/128 boundary — check scale_factor")
    else:
        print("  All weights within [-126, 126]. No boundary clipping.")

    return out_path


# ---------------------------------------------------------------------------
# CLI usage:
#   python3 extract_weights.py --emit-c --model-id 42 --out-dir ../src/hardcoded/ebpf/
# ---------------------------------------------------------------------------
if __name__ == "__main__" and "--emit-c" in sys.argv:
    import argparse
    ap = argparse.ArgumentParser(
        description="Emit C weight header for hardcoded eBPF model"
    )
    ap.add_argument("--emit-c",    action="store_true", help="Emit C header")
    ap.add_argument("--model-id",  type=int, default=42,  help="Model ID")
    ap.add_argument("--out-dir",   default="../src/hardcoded/ebpf/",
                    help="Output directory for the generated .h file")
    args = ap.parse_args()

    out = emit_c_hardcoded(
        model=model,
        scale_factor=SCALE_FACTOR,
        model_id=args.model_id,
        out_dir=args.out_dir,
    )
    print(f"\n[done] Include in model_{args.model_id}.c:\n"
          f'  #include "{os.path.basename(out)}"\n'
          f"  Then remove the placeholder W1/b1/W2/b2 arrays.")
