#!/usr/bin/env python3
"""
gen_nn_c.py  --  emit the PoC BPF-C for the recompilation study.

Goal of the PoC (what we are trying to prove/measure):
  Pipeline 1 bakes the model weights as C *literals*, so any new/modified
  model needs a full BCC clang recompile (~99.8% of the load cost). This
  PoC asks: can we compile the program ONCE per architecture (offline, ->
  a .o) and then deploy a new/modified model of the SAME architecture by
  only overwriting the weights in a frozen `.rodata` region + reloading,
  with NO clang -- and how much per-packet performance does that cost vs
  the literal build?

  To answer it we generate TWO functionally identical XDP programs from
  the SAME real weights, differing only in HOW the weights enter the math:

    nn_literal.bpf.c : weights as C literals (the current Pipeline-1 style,
                       clang folds them -> lean bytecode, but recompile per
                       model).
    nn_rodata.bpf.c  : weights read from `const volatile __s8 W[N]` placed
                       in `.rodata`; the loader (loader.c) injects the
                       actual values with bpf_map__set_initial_value() BEFORE
                       load and libbpf freezes .rodata read-only. Same .o
                       serves any weight set of this architecture -> NO
                       recompile, at the cost of one rodata load per weight.

  loader.c then loads both, prints each program's xlated instruction count
  (the per-packet cost proxy, same metric verify_prog_run.py uses) and times
  a from-.o redeploy with a different weight set (the recompile-free path).

Both programs read the 65-int8 input vector straight from the UDP payload
(runtime values) instead of rebuilding it from the feature maps/one-hots --
the feature plumbing is irrelevant to the weights-as-literal-vs-rodata
question this PoC isolates, and dropping it keeps the C small and robust to
compile on the first try. The NN math (65-4-4-7, two ReLU hidden layers,
argmax) is the real architecture, so the instruction-count comparison is
representative of Pipeline 1's dot product.

Run on the host (torch present) or inside Kathara (weights.json fallback):
    python3 shared/poc_rodata/gen_nn_c.py
-> writes nn_literal.bpf.c, nn_rodata.bpf.c, weights.bin, weights2.bin here.
"""
import os
import struct
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
SHARED_DIR = os.path.dirname(_HERE)
if SHARED_DIR not in sys.path:
    sys.path.insert(0, SHARED_DIR)

# Default 65-4-4-7 architecture (the trained FRR checkpoint).
N_IN, N_H1, N_H2, N_OUT = 65, 4, 4, 7
N_WEIGHTS = N_IN*N_H1 + N_H1 + N_H1*N_H2 + N_H2 + N_H2*N_OUT + N_OUT  # 319


def _weights():
    """Real int8 weights for the default architecture (torch or weights.json)."""
    from extract_weights import extract_weights_int8
    w = extract_weights_int8()
    if len(w) != N_WEIGHTS:
        raise SystemExit(f"expected {N_WEIGHTS} weights, got {len(w)}")
    return w


def _slices(w):
    fc1_w = w[0:N_IN*N_H1]
    fc1_b = w[N_IN*N_H1:N_IN*N_H1+N_H1]
    b2 = N_IN*N_H1+N_H1
    fc2_w = w[b2:b2+N_H1*N_H2]
    fc2_b = w[b2+N_H1*N_H2:b2+N_H1*N_H2+N_H2]
    b3 = b2+N_H1*N_H2+N_H2
    out_w = w[b3:b3+N_H2*N_OUT]
    out_b = w[b3+N_H2*N_OUT:b3+N_H2*N_OUT+N_OUT]
    # flat base offsets into W[] (rodata variant references W[base+...])
    off = {"fc1_w": 0, "fc1_b": N_IN*N_H1, "fc2_w": b2, "fc2_b": b2+N_H1*N_H2,
           "out_w": b3, "out_b": b3+N_H2*N_OUT}
    return fc1_w, fc1_b, fc2_w, fc2_b, out_w, out_b, off


def _emit(w, rodata: bool) -> str:
    """Generate the .bpf.c. If rodata, weights are W[k] reads; else literals."""
    fc1_w, fc1_b, fc2_w, fc2_b, out_w, out_b, off = _slices(w)

    def wref(flat_idx, value):
        # literal build bakes the value; rodata build reads the frozen array
        return f"((long long)W[{flat_idx}])" if rodata else f"{int(value)}LL"

    L = []
    A = L.append
    A("// AUTO-GENERATED by gen_nn_c.py -- do not edit by hand.")
    A("// PoC: %s weights (65-4-4-7 MLP, input read from UDP payload)."
      % ("rodata (frozen, injected at load)" if rodata else "literal (baked by clang)"))
    A("#include <linux/bpf.h>")
    A("#include <bpf/bpf_helpers.h>")
    A("")
    A(f"#define N_IN {N_IN}")
    A("")
    if rodata:
        A("// Weights live in .rodata. `const` -> .rodata section; `volatile`")
        A("// stops clang assuming the zero-initializer (the loader overwrites")
        A("// these before load via bpf_map__set_initial_value, then libbpf")
        A("// freezes the map read-only so the verifier treats them as known).")
        A(f"const volatile signed char W[{N_WEIGHTS}];")
        A("")
    A("SEC(\"xdp\")")
    A("int xdp_nn(struct xdp_md *ctx) {")
    A("    void *data     = (void *)(long)ctx->data;")
    A("    void *data_end = (void *)(long)ctx->data_end;")
    A("    signed char *p = data;")
    A("    // single bounds check covers p[0..N_IN-1] (constant indices below)")
    A("    if ((void *)(p + N_IN) > data_end) return XDP_PASS;")
    for i in range(N_IN):
        A(f"    long long iv{i} = (long long)p[{i}];")
    A("")
    # fc1
    for j in range(N_H1):
        terms = " + ".join(
            f"iv{i} * {wref(off['fc1_w']+j*N_IN+i, fc1_w[j*N_IN+i])}" for i in range(N_IN))
        bias = wref(off["fc1_b"]+j, fc1_b[j])
        A(f"    long long a1_{j} = {terms} + {bias};")
        A(f"    long long h1_{j} = a1_{j} > 0 ? a1_{j} : 0;")
    A("")
    # fc2
    for j in range(N_H2):
        terms = " + ".join(
            f"h1_{i} * {wref(off['fc2_w']+j*N_H1+i, fc2_w[j*N_H1+i])}" for i in range(N_H1))
        bias = wref(off["fc2_b"]+j, fc2_b[j])
        A(f"    long long a2_{j} = {terms} + {bias};")
        A(f"    long long h2_{j} = a2_{j} > 0 ? a2_{j} : 0;")
    A("")
    # out
    for j in range(N_OUT):
        terms = " + ".join(
            f"h2_{i} * {wref(off['out_w']+j*N_H2+i, out_w[j*N_H2+i])}" for i in range(N_H2))
        bias = wref(off["out_b"]+j, out_b[j])
        A(f"    long long o_{j} = {terms} + {bias};")
    A("")
    # argmax
    A("    long long best_val = o_0; int best_cls = 0;")
    for k in range(1, N_OUT):
        A(f"    if (o_{k} > best_val) {{ best_val = o_{k}; best_cls = {k}; }}")
    A("    return best_cls;   // proxy: we only load/verify, never attach")
    A("}")
    A("")
    A("char _license[] SEC(\"license\") = \"GPL\";")
    return "\n".join(L) + "\n"


def main():
    w = _weights()
    with open(os.path.join(_HERE, "nn_literal.bpf.c"), "w") as f:
        f.write(_emit(w, rodata=False))
    with open(os.path.join(_HERE, "nn_rodata.bpf.c"), "w") as f:
        f.write(_emit(w, rodata=True))
    # weight blobs for loader.c (int8 -> signed bytes)
    with open(os.path.join(_HERE, "weights.bin"), "wb") as f:
        f.write(struct.pack(f"{N_WEIGHTS}b", *[max(-128, min(127, int(x))) for x in w]))
    # a DIFFERENT model of the same architecture, to prove recompile-free redeploy
    w2 = [max(-128, min(127, -int(x))) for x in w]
    with open(os.path.join(_HERE, "weights2.bin"), "wb") as f:
        f.write(struct.pack(f"{N_WEIGHTS}b", *w2))
    print(f"wrote nn_literal.bpf.c, nn_rodata.bpf.c, weights.bin, weights2.bin "
          f"({N_WEIGHTS} int8 weights) in {_HERE}")


if __name__ == "__main__":
    main()
