#!/usr/bin/env python3
"""
gen_full_c.py  --  FULL-PATH variant of the recompilation PoC.

gen_sparse_c.py timed inference only. This one reproduces the ENTIRE per-packet
work the real Pipeline 1 does (the same work test_suite --kernel measures), so
the literal-vs-rodata latency is the production full-path delta, not the
inference-only worst case:

    eth/ip/udp/ipa parse (bounds checks)  [same both builds]
    link_state[6] via a real BPF_MAP_TYPE_ARRAY lookup (6 helper calls)  [same]
    ttl from ip->ttl                      [same]
    ingress_iface one-hot from ctx->ingress_ifindex via switch  [weights differ]
    node one-hot from ipa->model_id via switch                  [weights differ]
    fc1/fc2/out + argmax                  [weights differ]
    mac_table hash lookup + eth MAC rewrite + pkt_stats/cls_stats + bpf_redirect
                                          [same both builds]

Only the weight ACCESS differs literal-vs-rodata (immediate vs .rodata load);
every map lookup, parse and action instruction is identical, so they add the
same constant to both latencies and the delta% is diluted to the real
production figure. The single tail call (dispatcher -> model) is inlined here;
it adds ~one bpf_tail_call to both builds (negligible, same on both).

The loader (loader_full.c) crafts a real UDP/IPA frame, seeds link_state and
mac_table, sets ctx->ingress_ifindex, and BPF_PROG_TEST_RUNs it 1e6 times.

Run:  python3 gen_full_c.py -> nn_full_literal.bpf.c, nn_full_rodata.bpf.c
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
SHARED_DIR = os.path.dirname(_HERE)
if SHARED_DIR not in sys.path:
    sys.path.insert(0, SHARED_DIR)

N_LS, N_IFACE, N_TTL, N_NODE = 6, 6, 1, 52
N_IN = N_LS + N_IFACE + N_TTL + N_NODE   # 65
N_H1, N_H2, N_OUT = 4, 4, 7
N_WEIGHTS = N_IN*N_H1 + N_H1 + N_H1*N_H2 + N_H2 + N_H2*N_OUT + N_OUT  # 319
OFF_LS, OFF_IFACE, OFF_TTL, OFF_NODE = 0, N_LS, N_LS+N_IFACE, N_LS+N_IFACE+N_TTL
# kernel ifindex -> logical port 1..6 (loader sets ctx->ingress_ifindex = 2)
IFINDEX_TABLE = [2, 3, 4, 5, 6, 7]


def _weights():
    from extract_weights import extract_weights_int8
    w = extract_weights_int8()
    if len(w) != N_WEIGHTS:
        raise SystemExit(f"expected {N_WEIGHTS} weights, got {len(w)}")
    return w


def _slices(w):
    fc1_w = w[0:N_IN*N_H1]
    fc1_b = w[N_IN*N_H1:N_IN*N_H1+N_H1]
    b2 = N_IN*N_H1+N_H1
    fc2_w = w[b2:b2+N_H1*N_H2]
    fc2_b = w[b2+N_H1*N_H2:b2+N_H1*N_H2+N_H2]
    b3 = b2+N_H1*N_H2+N_H2
    out_w = w[b3:b3+N_H2*N_OUT]
    out_b = w[b3+N_H2*N_OUT:b3+N_H2*N_OUT+N_OUT]
    off = {"fc1_b": N_IN*N_H1, "fc2_w": b2, "fc2_b": b2+N_H1*N_H2,
           "out_w": b3, "out_b": b3+N_H2*N_OUT}
    return fc1_w, fc1_b, fc2_w, fc2_b, out_w, out_b, off


def _emit(w, rodata: bool) -> str:
    fc1_w, fc1_b, fc2_w, fc2_b, out_w, out_b, off = _slices(w)

    def wref(flat_idx, value):
        return f"((long long)W[{flat_idx}])" if rodata else f"{int(value)}LL"

    def fc1(j, pos):
        return j*N_IN + pos

    L = []
    A = L.append
    A("// AUTO-GENERATED by gen_full_c.py -- do not edit by hand.")
    A("// PoC FULL-PATH: %s weights, entire per-packet Pipeline-1 work."
      % ("rodata" if rodata else "literal"))
    A("#include <linux/bpf.h>")
    A("#include <linux/if_ether.h>")
    A("#include <linux/ip.h>")
    A("#include <linux/udp.h>")
    A("#include <linux/in.h>")
    A("#include <bpf/bpf_helpers.h>")
    A("#include <bpf/bpf_endian.h>")
    A("")
    A("struct ipa_hdr {")
    A("    __u8 model_id; __u8 model_type; __u8 param_size; __be16 scale_factor;")
    A("    __u8 input_size; __u8 output_size; __u8 hidden_layers; __u8 neurons_per_layer;")
    A("    __u8 n_feature_types;")
    A("    __u8 f0c,f0n,f1c,f1n,f2c,f2n,f3c,f3n; __u8 n_output_types; __u8 o0c,o0n;")
    A("} __attribute__((packed));")
    A("struct fwd_action { __u32 ifindex; __u8 src_mac[6]; __u8 dst_mac[6]; } __attribute__((packed));")
    A("")
    A("struct ls_vec { __u32 v[%d]; };" % N_LS)
    A("struct { __uint(type, BPF_MAP_TYPE_ARRAY); __uint(max_entries, 1);")
    A("         __type(key, __u32); __type(value, struct ls_vec); } link_state SEC(\".maps\");")
    A("struct { __uint(type, BPF_MAP_TYPE_ARRAY); __uint(max_entries, 3);")
    A("         __type(key, __u32); __type(value, __u64); } pkt_stats SEC(\".maps\");")
    A("struct { __uint(type, BPF_MAP_TYPE_ARRAY); __uint(max_entries, %d);" % N_OUT)
    A("         __type(key, __u32); __type(value, __u64); } cls_stats SEC(\".maps\");")
    A("struct { __uint(type, BPF_MAP_TYPE_HASH); __uint(max_entries, 16);")
    A("         __type(key, __u32); __type(value, struct fwd_action); } mac_table SEC(\".maps\");")
    A("")
    if rodata:
        A(f"const volatile signed char W[{N_WEIGHTS}];")
        A("")
    A("SEC(\"xdp\")")
    A("int xdp_full(struct xdp_md *ctx) {")
    A("    void *data = (void *)(long)ctx->data;")
    A("    void *data_end = (void *)(long)ctx->data_end;")
    A("    struct ethhdr *eth = data;")
    A("    if ((void *)(eth + 1) > data_end) return XDP_PASS;")
    A("    struct iphdr *ip = (struct iphdr *)(eth + 1);")
    A("    if ((void *)(ip + 1) > data_end) return XDP_PASS;")
    A("    __u8 ip_proto = *((__u8 *)ip + 9);")
    A("    if (ip_proto != 17) return XDP_PASS;")
    A("    __u32 ihl = (((__u8 *)ip)[0] & 0x0f) << 2;")
    A("    if (ihl < 20) return XDP_PASS;")
    A("    struct udphdr *udp = (struct udphdr *)((void *)ip + ihl);")
    A("    if ((void *)(udp + 1) > data_end) return XDP_PASS;")
    A("    if (udp->dest != bpf_htons(9999)) return XDP_PASS;")
    A("    struct ipa_hdr *ipa = (struct ipa_hdr *)(udp + 1);")
    A("    if ((void *)(ipa + 1) > data_end) return XDP_PASS;")
    A("")
    A("    long long ttl = (long long)ip->ttl;")
    A("    // link_state[6] from the real BPF array map (ONE lookup, vector-map layout) -- INPUT feature")
    A("    long long ls0=0,ls1=0,ls2=0,ls3=0,ls4=0,ls5=0;")
    A("    { __u32 z=0; struct ls_vec *lv = bpf_map_lookup_elem(&link_state,&z);")
    A("      if (lv) {")
    for i in range(N_LS):
        A(f"        ls{i}=(long long)(lv->v[{i}]);")
    A("      } }")
    A("    // ingress_iface one-hot: kernel ifindex -> logical 1..6")
    A("    __u32 _iface = 0;")
    A("    switch (ctx->ingress_ifindex) {")
    for logical, kern in enumerate(IFINDEX_TABLE, start=1):
        A(f"        case {kern}: _iface = {logical}; break;")
    A("        default: break;")
    A("    }")
    for j in range(N_H1):
        A(f"    long long w_iface_{j} = 0;")
    A("    switch (_iface) {")
    for k in range(1, N_IFACE + 1):
        assigns = " ".join(
            f"w_iface_{j} = {wref(fc1(j, OFF_IFACE + (k-1)), fc1_w[fc1(j, OFF_IFACE + (k-1))])};"
            for j in range(N_H1))
        A(f"        case {k}: {assigns} break;")
    A("        default: break;")
    A("    }")
    A("    // node one-hot from ipa->model_id")
    A("    __u32 _node = (__u32)ipa->model_id;")
    for j in range(N_H1):
        A(f"    long long w_node_{j} = 0;")
    A("    switch (_node) {")
    for k in range(N_NODE):
        assigns = " ".join(
            f"w_node_{j} = {wref(fc1(j, OFF_NODE + k), fc1_w[fc1(j, OFF_NODE + k)])};"
            for j in range(N_H1))
        A(f"        case {k}: {assigns} break;")
    A("        default: break;")
    A("    }")
    A("")
    for j in range(N_H1):
        ls_terms = " + ".join(
            f"ls{i} * {wref(fc1(j, OFF_LS + i), fc1_w[fc1(j, OFF_LS + i)])}" for i in range(N_LS))
        ttl_term = f"ttl * {wref(fc1(j, OFF_TTL), fc1_w[fc1(j, OFF_TTL)])}"
        bias = wref(off["fc1_b"]+j, fc1_b[j])
        A(f"    long long a1_{j} = {ls_terms} + {ttl_term} + w_iface_{j} + w_node_{j} + {bias};")
        A(f"    long long h1_{j} = a1_{j} > 0 ? a1_{j} : 0;")
    A("")
    for j in range(N_H2):
        terms = " + ".join(
            f"h1_{i} * {wref(off['fc2_w']+j*N_H1+i, fc2_w[j*N_H1+i])}" for i in range(N_H1))
        bias = wref(off["fc2_b"]+j, fc2_b[j])
        A(f"    long long a2_{j} = {terms} + {bias};")
        A(f"    long long h2_{j} = a2_{j} > 0 ? a2_{j} : 0;")
    A("")
    for j in range(N_OUT):
        terms = " + ".join(
            f"h2_{i} * {wref(off['out_w']+j*N_H2+i, out_w[j*N_H2+i])}" for i in range(N_H2))
        bias = wref(off["out_b"]+j, out_b[j])
        A(f"    long long o_{j} = {terms} + {bias};")
    A("")
    A("    long long best_val = o_0; int best_cls = 0;")
    for k in range(1, N_OUT):
        A(f"    if (o_{k} > best_val) {{ best_val = o_{k}; best_cls = {k}; }}")
    A("")
    A("    // --- action: DROP class, else mac_table lookup + eth rewrite + redirect ---")
    A(f"    if (best_cls >= {N_OUT - 1}) {{")
    A("        __u32 di = 2; __u64 *dv = bpf_map_lookup_elem(&pkt_stats, &di);")
    A("        if (dv) __sync_fetch_and_add(dv, 1);")
    A("        return XDP_DROP;")
    A("    }")
    A("    __u32 _cls = (__u32)best_cls;")
    A("    struct fwd_action *act = bpf_map_lookup_elem(&mac_table, &_cls);")
    A("    if (act) {")
    A("        __u32 hi = 0; __u64 *hv = bpf_map_lookup_elem(&pkt_stats, &hi);")
    A("        if (hv) __sync_fetch_and_add(hv, 1);")
    A("        __u64 *cv = bpf_map_lookup_elem(&cls_stats, &_cls);")
    A("        if (cv) __sync_fetch_and_add(cv, 1);")
    A("        __builtin_memcpy(eth->h_source, act->src_mac, 6);")
    A("        __builtin_memcpy(eth->h_dest,   act->dst_mac, 6);")
    A("        return bpf_redirect(act->ifindex, 0);")
    A("    }")
    A("    __u32 mi = 1; __u64 *mv = bpf_map_lookup_elem(&pkt_stats, &mi);")
    A("    if (mv) __sync_fetch_and_add(mv, 1);")
    A("    return XDP_PASS;")
    A("}")
    A("")
    A("char _license[] SEC(\"license\") = \"GPL\";")
    return "\n".join(L) + "\n"


def generate_literal_c(model_path: str = None) -> str:
    """Importable: return the FULL-PATH *literal* libbpf C for the default FRR
    descriptor (65-4-4-7), with real int8 weights from model_path (or the
    checked-in checkpoint when None). Used by method4_hardcoded_aot.py to build
    the AOT .o. rodata variant stays available via _emit(w, rodata=True)."""
    from extract_weights import extract_weights_int8
    w = extract_weights_int8(model_path) if model_path else _weights()
    if len(w) != N_WEIGHTS:
        raise SystemExit(f"expected {N_WEIGHTS} weights, got {len(w)}")
    return _emit(w, rodata=False)


def main():
    w = _weights()
    with open(os.path.join(_HERE, "nn_full_literal.bpf.c"), "w") as f:
        f.write(_emit(w, rodata=False))
    with open(os.path.join(_HERE, "nn_full_rodata.bpf.c"), "w") as f:
        f.write(_emit(w, rodata=True))
    print(f"wrote nn_full_literal.bpf.c, nn_full_rodata.bpf.c (full path, {N_WEIGHTS} weights) in {_HERE}")


if __name__ == "__main__":
    main()
