#!/usr/bin/env python3
"""
gen_sparse_c.py  --  FAITHFUL variant of the recompilation PoC.

gen_nn_c.py measures literal-vs-rodata on a DENSE 65-wide first layer (65 MACs
per neuron) with a volatile accumulator. That over-states the absolute cost:
the real Pipeline 1 (sparse route, ebpf_program.py) does NOT compute 65 dense
MACs. Its input vector is built feature-by-feature and most of it is one-hot:
the ingress-iface and node features each select exactly ONE weight per neuron
via a switch, so per packet only a handful of weights are actually touched
(6 dense link_state + 1 ttl + 1 iface + 1 node per neuron). That is why the
production literal build hits ~20 Mpps while the dense PoC only reaches ~10.

This generator reproduces that SPARSE computation structure (same one-hot
switches, same 6-wide dense link_state, same 65-4-4-7 weight layout and the
real weights) in a standalone libbpf XDP program, literal vs rodata. So the
literal build here should land near the production ~20 Mpps, and the
literal-vs-rodata delta is the REAL per-packet cost of frozen .rodata weights
on Pipeline 1 -- not the inflated dense number.

To stay self-contained (no BPF maps to seed, no xdp_md.ingress_ifindex to
forge on the fragile VM), the inputs are read from the packet payload instead
of the link_state map / ctx: p[0..5]=link_state, p[6]=ttl, p[7]=iface index
(1..6), p[8]=node index (0..51). The COMPUTATION is identical to production;
only the input SOURCE differs, which does not change the instruction mix we
measure. No volatile accumulator is needed -- the sparse layer has few live
terms and fits the 512B stack naturally, exactly like the real program.

Run:  python3 gen_sparse_c.py   -> nn_sparse_literal.bpf.c, nn_sparse_rodata.bpf.c
Then reuse loader.c:
    clang -O2 -g -target bpf -c nn_sparse_literal.bpf.c -o nn_sparse_literal.o
    clang -O2 -g -target bpf -c nn_sparse_rodata.bpf.c  -o nn_sparse_rodata.o
    sudo ./loader nn_sparse_literal.o nn_sparse_rodata.o weights.bin weights2.bin
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
SHARED_DIR = os.path.dirname(_HERE)
if SHARED_DIR not in sys.path:
    sys.path.insert(0, SHARED_DIR)

# Default 65-4-4-7 descriptor, real feature order [link_state, ingress_iface,
# ttl, node] (see model_meta._DEFAULT_FEATURE_TYPES).
N_LS, N_IFACE, N_TTL, N_NODE = 6, 6, 1, 52
N_IN = N_LS + N_IFACE + N_TTL + N_NODE   # 65
N_H1, N_H2, N_OUT = 4, 4, 7
N_WEIGHTS = N_IN*N_H1 + N_H1 + N_H1*N_H2 + N_H2 + N_H2*N_OUT + N_OUT  # 319
# per-feature offset inside a neuron's 65-wide fc1 weight row
OFF_LS, OFF_IFACE, OFF_TTL, OFF_NODE = 0, N_LS, N_LS+N_IFACE, N_LS+N_IFACE+N_TTL


def _weights():
    from extract_weights import extract_weights_int8
    w = extract_weights_int8()
    if len(w) != N_WEIGHTS:
        raise SystemExit(f"expected {N_WEIGHTS} weights, got {len(w)}")
    return w


def _slices(w):
    fc1_w = w[0:N_IN*N_H1]
    fc1_b = w[N_IN*N_H1:N_IN*N_H1+N_H1]
    b2 = N_IN*N_H1+N_H1
    fc2_w = w[b2:b2+N_H1*N_H2]
    fc2_b = w[b2+N_H1*N_H2:b2+N_H1*N_H2+N_H2]
    b3 = b2+N_H1*N_H2+N_H2
    out_w = w[b3:b3+N_H2*N_OUT]
    out_b = w[b3+N_H2*N_OUT:b3+N_H2*N_OUT+N_OUT]
    off = {"fc1_b": N_IN*N_H1, "fc2_w": b2, "fc2_b": b2+N_H1*N_H2,
           "out_w": b3, "out_b": b3+N_H2*N_OUT}
    return fc1_w, fc1_b, fc2_w, fc2_b, out_w, out_b, off


def _emit(w, rodata: bool) -> str:
    fc1_w, fc1_b, fc2_w, fc2_b, out_w, out_b, off = _slices(w)

    def wref(flat_idx, value):
        return f"((long long)W[{flat_idx}])" if rodata else f"{int(value)}LL"

    # flat index of fc1 weight (neuron j, input position pos in 0..64)
    def fc1(j, pos):
        return j*N_IN + pos

    L = []
    A = L.append
    A("// AUTO-GENERATED by gen_sparse_c.py -- do not edit by hand.")
    A("// PoC: %s weights, SPARSE structure (one-hot switches, 6 dense link_state)."
      % ("rodata (frozen, injected)" if rodata else "literal (baked)"))
    A("#include <linux/bpf.h>")
    A("#include <bpf/bpf_helpers.h>")
    A("")
    if rodata:
        A("// Weights in .rodata (loader injects real values before load, libbpf")
        A("// freezes it read-only). One-hot features read ONE W[] per neuron per")
        A("// packet via the switch below -- same access pattern as the literal")
        A("// build's per-case immediate, but a load instead of an immediate.")
        A(f"const volatile signed char W[{N_WEIGHTS}];")
        A("")
    A("SEC(\"xdp\")")
    A("int xdp_nn_sparse(struct xdp_md *ctx) {")
    A("    void *data     = (void *)(long)ctx->data;")
    A("    void *data_end = (void *)(long)ctx->data_end;")
    A("    signed char *p = data;")
    A("    if ((void *)(p + 9) > data_end) return XDP_PASS;")
    A("    // input sources (payload stands in for link_state map / ttl / ctx):")
    A("    long long ls0=(long long)p[0], ls1=(long long)p[1], ls2=(long long)p[2];")
    A("    long long ls3=(long long)p[3], ls4=(long long)p[4], ls5=(long long)p[5];")
    A("    long long ttl=(long long)p[6];")
    A("    int iface_idx = (int)p[7];   // logical ingress port 1..6 (0 = none)")
    A("    int node_idx  = (int)p[8];   // node one-hot index 0..51")
    A("")
    # --- ingress_iface one-hot: ONE switch total assigns w_iface_j for all neurons ---
    A("    // ingress_iface one-hot: one switch picks one weight per neuron")
    for j in range(N_H1):
        A(f"    long long w_iface_{j} = 0;")
    A("    switch (iface_idx) {")
    for k in range(1, N_IFACE + 1):   # logical port k -> row offset OFF_IFACE+(k-1)
        assigns = " ".join(
            f"w_iface_{j} = {wref(fc1(j, OFF_IFACE + (k-1)), fc1_w[fc1(j, OFF_IFACE + (k-1))])};"
            for j in range(N_H1))
        A(f"        case {k}: {assigns} break;")
    A("        default: break;")
    A("    }")
    # --- node one-hot: ONE switch total ---
    A("    // node one-hot: one switch picks one weight per neuron")
    for j in range(N_H1):
        A(f"    long long w_node_{j} = 0;")
    A("    switch (node_idx) {")
    for k in range(N_NODE):
        assigns = " ".join(
            f"w_node_{j} = {wref(fc1(j, OFF_NODE + k), fc1_w[fc1(j, OFF_NODE + k)])};"
            for j in range(N_H1))
        A(f"        case {k}: {assigns} break;")
    A("        default: break;")
    A("    }")
    A("")
    # --- fc1: 6 dense link_state + ttl + the two one-hot contributions ---
    for j in range(N_H1):
        ls_terms = " + ".join(
            f"ls{i} * {wref(fc1(j, OFF_LS + i), fc1_w[fc1(j, OFF_LS + i)])}" for i in range(N_LS))
        ttl_term = f"ttl * {wref(fc1(j, OFF_TTL), fc1_w[fc1(j, OFF_TTL)])}"
        bias = wref(off["fc1_b"]+j, fc1_b[j])
        A(f"    long long a1_{j} = {ls_terms} + {ttl_term} + w_iface_{j} + w_node_{j} + {bias};")
        A(f"    long long h1_{j} = a1_{j} > 0 ? a1_{j} : 0;")
    A("")
    # --- fc2 ---
    for j in range(N_H2):
        terms = " + ".join(
            f"h1_{i} * {wref(off['fc2_w']+j*N_H1+i, fc2_w[j*N_H1+i])}" for i in range(N_H1))
        bias = wref(off["fc2_b"]+j, fc2_b[j])
        A(f"    long long a2_{j} = {terms} + {bias};")
        A(f"    long long h2_{j} = a2_{j} > 0 ? a2_{j} : 0;")
    A("")
    # --- out ---
    for j in range(N_OUT):
        terms = " + ".join(
            f"h2_{i} * {wref(off['out_w']+j*N_H2+i, out_w[j*N_H2+i])}" for i in range(N_H2))
        bias = wref(off["out_b"]+j, out_b[j])
        A(f"    long long o_{j} = {terms} + {bias};")
    A("")
    A("    long long best_val = o_0; int best_cls = 0;")
    for k in range(1, N_OUT):
        A(f"    if (o_{k} > best_val) {{ best_val = o_{k}; best_cls = {k}; }}")
    A("    return best_cls;")
    A("}")
    A("")
    A("char _license[] SEC(\"license\") = \"GPL\";")
    return "\n".join(L) + "\n"


def main():
    w = _weights()
    with open(os.path.join(_HERE, "nn_sparse_literal.bpf.c"), "w") as f:
        f.write(_emit(w, rodata=False))
    with open(os.path.join(_HERE, "nn_sparse_rodata.bpf.c"), "w") as f:
        f.write(_emit(w, rodata=True))
    print(f"wrote nn_sparse_literal.bpf.c, nn_sparse_rodata.bpf.c "
          f"(sparse structure, {N_WEIGHTS} weights) in {_HERE}")
    print("weights.bin / weights2.bin from gen_nn_c.py are reused as-is.")


if __name__ == "__main__":
    main()
