// AUTO-GENERATED by gen_full_c.py -- do not edit by hand.
// PoC FULL-PATH: literal weights, entire per-packet Pipeline-1 work.
#include <linux/bpf.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/udp.h>
#include <linux/in.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>

struct ipa_hdr {
    __u8 model_id; __u8 model_type; __u8 param_size; __be16 scale_factor;
    __u8 input_size; __u8 output_size; __u8 hidden_layers; __u8 neurons_per_layer;
    __u8 n_feature_types;
    __u8 f0c,f0n,f1c,f1n,f2c,f2n,f3c,f3n; __u8 n_output_types; __u8 o0c,o0n;
} __attribute__((packed));
struct fwd_action { __u32 ifindex; __u8 src_mac[6]; __u8 dst_mac[6]; } __attribute__((packed));

struct { __uint(type, BPF_MAP_TYPE_ARRAY); __uint(max_entries, 6);
         __type(key, __u32); __type(value, __u32); } link_state SEC(".maps");
struct { __uint(type, BPF_MAP_TYPE_ARRAY); __uint(max_entries, 3);
         __type(key, __u32); __type(value, __u64); } pkt_stats SEC(".maps");
struct { __uint(type, BPF_MAP_TYPE_ARRAY); __uint(max_entries, 7);
         __type(key, __u32); __type(value, __u64); } cls_stats SEC(".maps");
struct { __uint(type, BPF_MAP_TYPE_HASH); __uint(max_entries, 16);
         __type(key, __u32); __type(value, struct fwd_action); } mac_table SEC(".maps");

SEC("xdp")
int xdp_full(struct xdp_md *ctx) {
    void *data = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return XDP_PASS;
    struct iphdr *ip = (struct iphdr *)(eth + 1);
    if ((void *)(ip + 1) > data_end) return XDP_PASS;
    __u8 ip_proto = *((__u8 *)ip + 9);
    if (ip_proto != 17) return XDP_PASS;
    __u32 ihl = (((__u8 *)ip)[0] & 0x0f) << 2;
    if (ihl < 20) return XDP_PASS;
    struct udphdr *udp = (struct udphdr *)((void *)ip + ihl);
    if ((void *)(udp + 1) > data_end) return XDP_PASS;
    if (udp->dest != bpf_htons(9999)) return XDP_PASS;
    struct ipa_hdr *ipa = (struct ipa_hdr *)(udp + 1);
    if ((void *)(ipa + 1) > data_end) return XDP_PASS;

    long long ttl = (long long)ip->ttl;
    // link_state[6] from the real BPF array map (6 helper lookups) -- INPUT feature
    long long ls0=0,ls1=0,ls2=0,ls3=0,ls4=0,ls5=0;
    { __u32 k; __u32 *v;
      k=0; v=bpf_map_lookup_elem(&link_state,&k); if(v) ls0=(long long)(*v);
      k=1; v=bpf_map_lookup_elem(&link_state,&k); if(v) ls1=(long long)(*v);
      k=2; v=bpf_map_lookup_elem(&link_state,&k); if(v) ls2=(long long)(*v);
      k=3; v=bpf_map_lookup_elem(&link_state,&k); if(v) ls3=(long long)(*v);
      k=4; v=bpf_map_lookup_elem(&link_state,&k); if(v) ls4=(long long)(*v);
      k=5; v=bpf_map_lookup_elem(&link_state,&k); if(v) ls5=(long long)(*v);
    }
    // ingress_iface one-hot: kernel ifindex -> logical 1..6
    __u32 _iface = 0;
    switch (ctx->ingress_ifindex) {
        case 2: _iface = 1; break;
        case 3: _iface = 2; break;
        case 4: _iface = 3; break;
        case 5: _iface = 4; break;
        case 6: _iface = 5; break;
        case 7: _iface = 6; break;
        default: break;
    }
    long long w_iface_0 = 0;
    long long w_iface_1 = 0;
    long long w_iface_2 = 0;
    long long w_iface_3 = 0;
    switch (_iface) {
        case 1: w_iface_0 = -1LL; w_iface_1 = 0LL; w_iface_2 = 9LL; w_iface_3 = 6LL; break;
        case 2: w_iface_0 = -9LL; w_iface_1 = -6LL; w_iface_2 = -4LL; w_iface_3 = -13LL; break;
        case 3: w_iface_0 = -1LL; w_iface_1 = 14LL; w_iface_2 = -6LL; w_iface_3 = 7LL; break;
        case 4: w_iface_0 = -2LL; w_iface_1 = -20LL; w_iface_2 = -13LL; w_iface_3 = 7LL; break;
        case 5: w_iface_0 = -11LL; w_iface_1 = -9LL; w_iface_2 = -3LL; w_iface_3 = 2LL; break;
        case 6: w_iface_0 = 27LL; w_iface_1 = 0LL; w_iface_2 = 0LL; w_iface_3 = 5LL; break;
        default: break;
    }
    // node one-hot from ipa->model_id
    __u32 _node = (__u32)ipa->model_id;
    long long w_node_0 = 0;
    long long w_node_1 = 0;
    long long w_node_2 = 0;
    long long w_node_3 = 0;
    switch (_node) {
        case 0: w_node_0 = 27LL; w_node_1 = -6LL; w_node_2 = 7LL; w_node_3 = 0LL; break;
        case 1: w_node_0 = 12LL; w_node_1 = -6LL; w_node_2 = 9LL; w_node_3 = -7LL; break;
        case 2: w_node_0 = 8LL; w_node_1 = -14LL; w_node_2 = -9LL; w_node_3 = 17LL; break;
        case 3: w_node_0 = -3LL; w_node_1 = -50LL; w_node_2 = -31LL; w_node_3 = -18LL; break;
        case 4: w_node_0 = 6LL; w_node_1 = 3LL; w_node_2 = -4LL; w_node_3 = 19LL; break;
        case 5: w_node_0 = 18LL; w_node_1 = -11LL; w_node_2 = 9LL; w_node_3 = 24LL; break;
        case 6: w_node_0 = 12LL; w_node_1 = 13LL; w_node_2 = -4LL; w_node_3 = 10LL; break;
        case 7: w_node_0 = -3LL; w_node_1 = -1LL; w_node_2 = -20LL; w_node_3 = 19LL; break;
        case 8: w_node_0 = -4LL; w_node_1 = 1LL; w_node_2 = -9LL; w_node_3 = 15LL; break;
        case 9: w_node_0 = 7LL; w_node_1 = 1LL; w_node_2 = -11LL; w_node_3 = 4LL; break;
        case 10: w_node_0 = 0LL; w_node_1 = 4LL; w_node_2 = -7LL; w_node_3 = 13LL; break;
        case 11: w_node_0 = -2LL; w_node_1 = 21LL; w_node_2 = -5LL; w_node_3 = -27LL; break;
        case 12: w_node_0 = 0LL; w_node_1 = 6LL; w_node_2 = -13LL; w_node_3 = 3LL; break;
        case 13: w_node_0 = -39LL; w_node_1 = -15LL; w_node_2 = -1LL; w_node_3 = -13LL; break;
        case 14: w_node_0 = 14LL; w_node_1 = -3LL; w_node_2 = 9LL; w_node_3 = -5LL; break;
        case 15: w_node_0 = 46LL; w_node_1 = 29LL; w_node_2 = 46LL; w_node_3 = 15LL; break;
        case 16: w_node_0 = 7LL; w_node_1 = -14LL; w_node_2 = 19LL; w_node_3 = 8LL; break;
        case 17: w_node_0 = 2LL; w_node_1 = 5LL; w_node_2 = -14LL; w_node_3 = 5LL; break;
        case 18: w_node_0 = 14LL; w_node_1 = -9LL; w_node_2 = 19LL; w_node_3 = 10LL; break;
        case 19: w_node_0 = 9LL; w_node_1 = -13LL; w_node_2 = 18LL; w_node_3 = 9LL; break;
        case 20: w_node_0 = -4LL; w_node_1 = 4LL; w_node_2 = -9LL; w_node_3 = 16LL; break;
        case 21: w_node_0 = -13LL; w_node_1 = -14LL; w_node_2 = 27LL; w_node_3 = 18LL; break;
        case 22: w_node_0 = -53LL; w_node_1 = -19LL; w_node_2 = 35LL; w_node_3 = 18LL; break;
        case 23: w_node_0 = 17LL; w_node_1 = 2LL; w_node_2 = 15LL; w_node_3 = -8LL; break;
        case 24: w_node_0 = -39LL; w_node_1 = -36LL; w_node_2 = -42LL; w_node_3 = -26LL; break;
        case 25: w_node_0 = 42LL; w_node_1 = 11LL; w_node_2 = 4LL; w_node_3 = -18LL; break;
        case 26: w_node_0 = -4LL; w_node_1 = 1LL; w_node_2 = -9LL; w_node_3 = 14LL; break;
        case 27: w_node_0 = 17LL; w_node_1 = 6LL; w_node_2 = -8LL; w_node_3 = 12LL; break;
        case 28: w_node_0 = -26LL; w_node_1 = 2LL; w_node_2 = -6LL; w_node_3 = -23LL; break;
        case 29: w_node_0 = 3LL; w_node_1 = 5LL; w_node_2 = -9LL; w_node_3 = 5LL; break;
        case 30: w_node_0 = 9LL; w_node_1 = -15LL; w_node_2 = 11LL; w_node_3 = 6LL; break;
        case 31: w_node_0 = 2LL; w_node_1 = -33LL; w_node_2 = -27LL; w_node_3 = 15LL; break;
        case 32: w_node_0 = -19LL; w_node_1 = 14LL; w_node_2 = -2LL; w_node_3 = -7LL; break;
        case 33: w_node_0 = 2LL; w_node_1 = 5LL; w_node_2 = -15LL; w_node_3 = 6LL; break;
        case 34: w_node_0 = 27LL; w_node_1 = 1LL; w_node_2 = 20LL; w_node_3 = -20LL; break;
        case 35: w_node_0 = 11LL; w_node_1 = -4LL; w_node_2 = -7LL; w_node_3 = -3LL; break;
        case 36: w_node_0 = 0LL; w_node_1 = 6LL; w_node_2 = -13LL; w_node_3 = 3LL; break;
        case 37: w_node_0 = -2LL; w_node_1 = 35LL; w_node_2 = -10LL; w_node_3 = 0LL; break;
        case 38: w_node_0 = 7LL; w_node_1 = 8LL; w_node_2 = 1LL; w_node_3 = -39LL; break;
        case 39: w_node_0 = 13LL; w_node_1 = 0LL; w_node_2 = 8LL; w_node_3 = -8LL; break;
        case 40: w_node_0 = 2LL; w_node_1 = 6LL; w_node_2 = -13LL; w_node_3 = 4LL; break;
        case 41: w_node_0 = 1LL; w_node_1 = -3LL; w_node_2 = -7LL; w_node_3 = 13LL; break;
        case 42: w_node_0 = 15LL; w_node_1 = -10LL; w_node_2 = 4LL; w_node_3 = 0LL; break;
        case 43: w_node_0 = -40LL; w_node_1 = -14LL; w_node_2 = 8LL; w_node_3 = -29LL; break;
        case 44: w_node_0 = 22LL; w_node_1 = 9LL; w_node_2 = -7LL; w_node_3 = 2LL; break;
        case 45: w_node_0 = -7LL; w_node_1 = 28LL; w_node_2 = 9LL; w_node_3 = -38LL; break;
        case 46: w_node_0 = 8LL; w_node_1 = -4LL; w_node_2 = -11LL; w_node_3 = 3LL; break;
        case 47: w_node_0 = -5LL; w_node_1 = 1LL; w_node_2 = -10LL; w_node_3 = 13LL; break;
        case 48: w_node_0 = -33LL; w_node_1 = -2LL; w_node_2 = 16LL; w_node_3 = -10LL; break;
        case 49: w_node_0 = 16LL; w_node_1 = 2LL; w_node_2 = 13LL; w_node_3 = 24LL; break;
        case 50: w_node_0 = 0LL; w_node_1 = 0LL; w_node_2 = 0LL; w_node_3 = 0LL; break;
        case 51: w_node_0 = 2LL; w_node_1 = 12LL; w_node_2 = -6LL; w_node_3 = -7LL; break;
        default: break;
    }

    long long a1_0 = ls0 * 8LL + ls1 * 7LL + ls2 * 33LL + ls3 * -11LL + ls4 * 38LL + ls5 * 1LL + ttl * 11LL + w_iface_0 + w_node_0 + -36LL;
    long long h1_0 = a1_0 > 0 ? a1_0 : 0;
    long long a1_1 = ls0 * 3LL + ls1 * 1LL + ls2 * 1LL + ls3 * 20LL + ls4 * 2LL + ls5 * 16LL + ttl * 9LL + w_iface_1 + w_node_1 + -15LL;
    long long h1_1 = a1_1 > 0 ? a1_1 : 0;
    long long a1_2 = ls0 * -16LL + ls1 * -1LL + ls2 * 28LL + ls3 * 15LL + ls4 * 3LL + ls5 * 1LL + ttl * -5LL + w_iface_2 + w_node_2 + 1LL;
    long long h1_2 = a1_2 > 0 ? a1_2 : 0;
    long long a1_3 = ls0 * -9LL + ls1 * 31LL + ls2 * 6LL + ls3 * -10LL + ls4 * -10LL + ls5 * 0LL + ttl * 2LL + w_iface_3 + w_node_3 + 12LL;
    long long h1_3 = a1_3 > 0 ? a1_3 : 0;

    long long a2_0 = h1_0 * 51LL + h1_1 * 32LL + h1_2 * 8LL + h1_3 * -70LL + 6LL;
    long long h2_0 = a2_0 > 0 ? a2_0 : 0;
    long long a2_1 = h1_0 * 122LL + h1_1 * -82LL + h1_2 * 21LL + h1_3 * 9LL + -2LL;
    long long h2_1 = a2_1 > 0 ? a2_1 : 0;
    long long a2_2 = h1_0 * 49LL + h1_1 * 46LL + h1_2 * -30LL + h1_3 * 61LL + -20LL;
    long long h2_2 = a2_2 > 0 ? a2_2 : 0;
    long long a2_3 = h1_0 * -27LL + h1_1 * 9LL + h1_2 * 96LL + h1_3 * 40LL + 12LL;
    long long h2_3 = a2_3 > 0 ? a2_3 : 0;

    long long o_0 = h2_0 * 37LL + h2_1 * -6LL + h2_2 * 54LL + h2_3 * -82LL + -22LL;
    long long o_1 = h2_0 * -70LL + h2_1 * 16LL + h2_2 * 45LL + h2_3 * 3LL + -12LL;
    long long o_2 = h2_0 * 10LL + h2_1 * 51LL + h2_2 * -49LL + h2_3 * 37LL + -57LL;
    long long o_3 = h2_0 * 45LL + h2_1 * -121LL + h2_2 * -6LL + h2_3 * 43LL + 18LL;
    long long o_4 = h2_0 * -22LL + h2_1 * 65LL + h2_2 * -47LL + h2_3 * -33LL + 75LL;
    long long o_5 = h2_0 * 9LL + h2_1 * -8LL + h2_2 * 8LL + h2_3 * 27LL + 18LL;
    long long o_6 = h2_0 * -5LL + h2_1 * -5LL + h2_2 * -4LL + h2_3 * -13LL + -18LL;

    long long best_val = o_0; int best_cls = 0;
    if (o_1 > best_val) { best_val = o_1; best_cls = 1; }
    if (o_2 > best_val) { best_val = o_2; best_cls = 2; }
    if (o_3 > best_val) { best_val = o_3; best_cls = 3; }
    if (o_4 > best_val) { best_val = o_4; best_cls = 4; }
    if (o_5 > best_val) { best_val = o_5; best_cls = 5; }
    if (o_6 > best_val) { best_val = o_6; best_cls = 6; }

    // --- action: DROP class, else mac_table lookup + eth rewrite + redirect ---
    if (best_cls >= 6) {
        __u32 di = 2; __u64 *dv = bpf_map_lookup_elem(&pkt_stats, &di);
        if (dv) __sync_fetch_and_add(dv, 1);
        return XDP_DROP;
    }
    __u32 _cls = (__u32)best_cls;
    struct fwd_action *act = bpf_map_lookup_elem(&mac_table, &_cls);
    if (act) {
        __u32 hi = 0; __u64 *hv = bpf_map_lookup_elem(&pkt_stats, &hi);
        if (hv) __sync_fetch_and_add(hv, 1);
        __u64 *cv = bpf_map_lookup_elem(&cls_stats, &_cls);
        if (cv) __sync_fetch_and_add(cv, 1);
        __builtin_memcpy(eth->h_source, act->src_mac, 6);
        __builtin_memcpy(eth->h_dest,   act->dst_mac, 6);
        return bpf_redirect(act->ifindex, 0);
    }
    __u32 mi = 1; __u64 *mv = bpf_map_lookup_elem(&pkt_stats, &mi);
    if (mv) __sync_fetch_and_add(mv, 1);
    return XDP_PASS;
}

char _license[] SEC("license") = "GPL";
