// AUTO-GENERATED by gen_nn_c.py -- do not edit by hand.
// PoC: literal (baked by clang) weights (65-4-4-7 MLP, input read from UDP payload).
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

#define N_IN 65

SEC("xdp")
int xdp_nn(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    signed char *p = data;
    // single bounds check covers p[0..N_IN-1] (constant indices below)
    if ((void *)(p + N_IN) > data_end) return XDP_PASS;

    long long a1_0 = ((long long)p[0]) * 8LL + ((long long)p[1]) * 7LL + ((long long)p[2]) * 33LL + ((long long)p[3]) * -11LL + ((long long)p[4]) * 38LL + ((long long)p[5]) * 1LL + ((long long)p[6]) * -1LL + ((long long)p[7]) * -9LL + ((long long)p[8]) * -1LL + ((long long)p[9]) * -2LL + ((long long)p[10]) * -11LL + ((long long)p[11]) * 27LL + ((long long)p[12]) * 11LL + ((long long)p[13]) * 27LL + ((long long)p[14]) * 12LL + ((long long)p[15]) * 8LL + ((long long)p[16]) * -3LL + ((long long)p[17]) * 6LL + ((long long)p[18]) * 18LL + ((long long)p[19]) * 12LL + ((long long)p[20]) * -3LL + ((long long)p[21]) * -4LL + ((long long)p[22]) * 7LL + ((long long)p[23]) * 0LL + ((long long)p[24]) * -2LL + ((long long)p[25]) * 0LL + ((long long)p[26]) * -39LL + ((long long)p[27]) * 14LL + ((long long)p[28]) * 46LL + ((long long)p[29]) * 7LL + ((long long)p[30]) * 2LL + ((long long)p[31]) * 14LL + ((long long)p[32]) * 9LL + ((long long)p[33]) * -4LL + ((long long)p[34]) * -13LL + ((long long)p[35]) * -53LL + ((long long)p[36]) * 17LL + ((long long)p[37]) * -39LL + ((long long)p[38]) * 42LL + ((long long)p[39]) * -4LL + ((long long)p[40]) * 17LL + ((long long)p[41]) * -26LL + ((long long)p[42]) * 3LL + ((long long)p[43]) * 9LL + ((long long)p[44]) * 2LL + ((long long)p[45]) * -19LL + ((long long)p[46]) * 2LL + ((long long)p[47]) * 27LL + ((long long)p[48]) * 11LL + ((long long)p[49]) * 0LL + ((long long)p[50]) * -2LL + ((long long)p[51]) * 7LL + ((long long)p[52]) * 13LL + ((long long)p[53]) * 2LL + ((long long)p[54]) * 1LL + ((long long)p[55]) * 15LL + ((long long)p[56]) * -40LL + ((long long)p[57]) * 22LL + ((long long)p[58]) * -7LL + ((long long)p[59]) * 8LL + ((long long)p[60]) * -5LL + ((long long)p[61]) * -33LL + ((long long)p[62]) * 16LL + ((long long)p[63]) * 0LL + ((long long)p[64]) * 2LL + -36LL;
    long long h1_0 = a1_0 > 0 ? a1_0 : 0;
    long long a1_1 = ((long long)p[0]) * 3LL + ((long long)p[1]) * 1LL + ((long long)p[2]) * 1LL + ((long long)p[3]) * 20LL + ((long long)p[4]) * 2LL + ((long long)p[5]) * 16LL + ((long long)p[6]) * 0LL + ((long long)p[7]) * -6LL + ((long long)p[8]) * 14LL + ((long long)p[9]) * -20LL + ((long long)p[10]) * -9LL + ((long long)p[11]) * 0LL + ((long long)p[12]) * 9LL + ((long long)p[13]) * -6LL + ((long long)p[14]) * -6LL + ((long long)p[15]) * -14LL + ((long long)p[16]) * -50LL + ((long long)p[17]) * 3LL + ((long long)p[18]) * -11LL + ((long long)p[19]) * 13LL + ((long long)p[20]) * -1LL + ((long long)p[21]) * 1LL + ((long long)p[22]) * 1LL + ((long long)p[23]) * 4LL + ((long long)p[24]) * 21LL + ((long long)p[25]) * 6LL + ((long long)p[26]) * -15LL + ((long long)p[27]) * -3LL + ((long long)p[28]) * 29LL + ((long long)p[29]) * -14LL + ((long long)p[30]) * 5LL + ((long long)p[31]) * -9LL + ((long long)p[32]) * -13LL + ((long long)p[33]) * 4LL + ((long long)p[34]) * -14LL + ((long long)p[35]) * -19LL + ((long long)p[36]) * 2LL + ((long long)p[37]) * -36LL + ((long long)p[38]) * 11LL + ((long long)p[39]) * 1LL + ((long long)p[40]) * 6LL + ((long long)p[41]) * 2LL + ((long long)p[42]) * 5LL + ((long long)p[43]) * -15LL + ((long long)p[44]) * -33LL + ((long long)p[45]) * 14LL + ((long long)p[46]) * 5LL + ((long long)p[47]) * 1LL + ((long long)p[48]) * -4LL + ((long long)p[49]) * 6LL + ((long long)p[50]) * 35LL + ((long long)p[51]) * 8LL + ((long long)p[52]) * 0LL + ((long long)p[53]) * 6LL + ((long long)p[54]) * -3LL + ((long long)p[55]) * -10LL + ((long long)p[56]) * -14LL + ((long long)p[57]) * 9LL + ((long long)p[58]) * 28LL + ((long long)p[59]) * -4LL + ((long long)p[60]) * 1LL + ((long long)p[61]) * -2LL + ((long long)p[62]) * 2LL + ((long long)p[63]) * 0LL + ((long long)p[64]) * 12LL + -15LL;
    long long h1_1 = a1_1 > 0 ? a1_1 : 0;
    long long a1_2 = ((long long)p[0]) * -16LL + ((long long)p[1]) * -1LL + ((long long)p[2]) * 28LL + ((long long)p[3]) * 15LL + ((long long)p[4]) * 3LL + ((long long)p[5]) * 1LL + ((long long)p[6]) * 9LL + ((long long)p[7]) * -4LL + ((long long)p[8]) * -6LL + ((long long)p[9]) * -13LL + ((long long)p[10]) * -3LL + ((long long)p[11]) * 0LL + ((long long)p[12]) * -5LL + ((long long)p[13]) * 7LL + ((long long)p[14]) * 9LL + ((long long)p[15]) * -9LL + ((long long)p[16]) * -31LL + ((long long)p[17]) * -4LL + ((long long)p[18]) * 9LL + ((long long)p[19]) * -4LL + ((long long)p[20]) * -20LL + ((long long)p[21]) * -9LL + ((long long)p[22]) * -11LL + ((long long)p[23]) * -7LL + ((long long)p[24]) * -5LL + ((long long)p[25]) * -13LL + ((long long)p[26]) * -1LL + ((long long)p[27]) * 9LL + ((long long)p[28]) * 46LL + ((long long)p[29]) * 19LL + ((long long)p[30]) * -14LL + ((long long)p[31]) * 19LL + ((long long)p[32]) * 18LL + ((long long)p[33]) * -9LL + ((long long)p[34]) * 27LL + ((long long)p[35]) * 35LL + ((long long)p[36]) * 15LL + ((long long)p[37]) * -42LL + ((long long)p[38]) * 4LL + ((long long)p[39]) * -9LL + ((long long)p[40]) * -8LL + ((long long)p[41]) * -6LL + ((long long)p[42]) * -9LL + ((long long)p[43]) * 11LL + ((long long)p[44]) * -27LL + ((long long)p[45]) * -2LL + ((long long)p[46]) * -15LL + ((long long)p[47]) * 20LL + ((long long)p[48]) * -7LL + ((long long)p[49]) * -13LL + ((long long)p[50]) * -10LL + ((long long)p[51]) * 1LL + ((long long)p[52]) * 8LL + ((long long)p[53]) * -13LL + ((long long)p[54]) * -7LL + ((long long)p[55]) * 4LL + ((long long)p[56]) * 8LL + ((long long)p[57]) * -7LL + ((long long)p[58]) * 9LL + ((long long)p[59]) * -11LL + ((long long)p[60]) * -10LL + ((long long)p[61]) * 16LL + ((long long)p[62]) * 13LL + ((long long)p[63]) * 0LL + ((long long)p[64]) * -6LL + 1LL;
    long long h1_2 = a1_2 > 0 ? a1_2 : 0;
    long long a1_3 = ((long long)p[0]) * -9LL + ((long long)p[1]) * 31LL + ((long long)p[2]) * 6LL + ((long long)p[3]) * -10LL + ((long long)p[4]) * -10LL + ((long long)p[5]) * 0LL + ((long long)p[6]) * 6LL + ((long long)p[7]) * -13LL + ((long long)p[8]) * 7LL + ((long long)p[9]) * 7LL + ((long long)p[10]) * 2LL + ((long long)p[11]) * 5LL + ((long long)p[12]) * 2LL + ((long long)p[13]) * 0LL + ((long long)p[14]) * -7LL + ((long long)p[15]) * 17LL + ((long long)p[16]) * -18LL + ((long long)p[17]) * 19LL + ((long long)p[18]) * 24LL + ((long long)p[19]) * 10LL + ((long long)p[20]) * 19LL + ((long long)p[21]) * 15LL + ((long long)p[22]) * 4LL + ((long long)p[23]) * 13LL + ((long long)p[24]) * -27LL + ((long long)p[25]) * 3LL + ((long long)p[26]) * -13LL + ((long long)p[27]) * -5LL + ((long long)p[28]) * 15LL + ((long long)p[29]) * 8LL + ((long long)p[30]) * 5LL + ((long long)p[31]) * 10LL + ((long long)p[32]) * 9LL + ((long long)p[33]) * 16LL + ((long long)p[34]) * 18LL + ((long long)p[35]) * 18LL + ((long long)p[36]) * -8LL + ((long long)p[37]) * -26LL + ((long long)p[38]) * -18LL + ((long long)p[39]) * 14LL + ((long long)p[40]) * 12LL + ((long long)p[41]) * -23LL + ((long long)p[42]) * 5LL + ((long long)p[43]) * 6LL + ((long long)p[44]) * 15LL + ((long long)p[45]) * -7LL + ((long long)p[46]) * 6LL + ((long long)p[47]) * -20LL + ((long long)p[48]) * -3LL + ((long long)p[49]) * 3LL + ((long long)p[50]) * 0LL + ((long long)p[51]) * -39LL + ((long long)p[52]) * -8LL + ((long long)p[53]) * 4LL + ((long long)p[54]) * 13LL + ((long long)p[55]) * 0LL + ((long long)p[56]) * -29LL + ((long long)p[57]) * 2LL + ((long long)p[58]) * -38LL + ((long long)p[59]) * 3LL + ((long long)p[60]) * 13LL + ((long long)p[61]) * -10LL + ((long long)p[62]) * 24LL + ((long long)p[63]) * 0LL + ((long long)p[64]) * -7LL + 12LL;
    long long h1_3 = a1_3 > 0 ? a1_3 : 0;

    long long a2_0 = h1_0 * 51LL + h1_1 * 32LL + h1_2 * 8LL + h1_3 * -70LL + 6LL;
    long long h2_0 = a2_0 > 0 ? a2_0 : 0;
    long long a2_1 = h1_0 * 122LL + h1_1 * -82LL + h1_2 * 21LL + h1_3 * 9LL + -2LL;
    long long h2_1 = a2_1 > 0 ? a2_1 : 0;
    long long a2_2 = h1_0 * 49LL + h1_1 * 46LL + h1_2 * -30LL + h1_3 * 61LL + -20LL;
    long long h2_2 = a2_2 > 0 ? a2_2 : 0;
    long long a2_3 = h1_0 * -27LL + h1_1 * 9LL + h1_2 * 96LL + h1_3 * 40LL + 12LL;
    long long h2_3 = a2_3 > 0 ? a2_3 : 0;

    long long o_0 = h2_0 * 37LL + h2_1 * -6LL + h2_2 * 54LL + h2_3 * -82LL + -22LL;
    long long o_1 = h2_0 * -70LL + h2_1 * 16LL + h2_2 * 45LL + h2_3 * 3LL + -12LL;
    long long o_2 = h2_0 * 10LL + h2_1 * 51LL + h2_2 * -49LL + h2_3 * 37LL + -57LL;
    long long o_3 = h2_0 * 45LL + h2_1 * -121LL + h2_2 * -6LL + h2_3 * 43LL + 18LL;
    long long o_4 = h2_0 * -22LL + h2_1 * 65LL + h2_2 * -47LL + h2_3 * -33LL + 75LL;
    long long o_5 = h2_0 * 9LL + h2_1 * -8LL + h2_2 * 8LL + h2_3 * 27LL + 18LL;
    long long o_6 = h2_0 * -5LL + h2_1 * -5LL + h2_2 * -4LL + h2_3 * -13LL + -18LL;

    long long best_val = o_0; int best_cls = 0;
    if (o_1 > best_val) { best_val = o_1; best_cls = 1; }
    if (o_2 > best_val) { best_val = o_2; best_cls = 2; }
    if (o_3 > best_val) { best_val = o_3; best_cls = 3; }
    if (o_4 > best_val) { best_val = o_4; best_cls = 4; }
    if (o_5 > best_val) { best_val = o_5; best_cls = 5; }
    if (o_6 > best_val) { best_val = o_6; best_cls = 6; }
    return best_cls;   // proxy: we only load/verify, never attach
}

char _license[] SEC("license") = "GPL";
