// AUTO-GENERATED by gen_nn_c.py -- do not edit by hand.
// PoC: literal (baked by clang) weights (65-4-4-7 MLP, input read from UDP payload).
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

#define N_IN 65

SEC("xdp")
int xdp_nn(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    signed char *p = data;
    // single bounds check covers p[0..N_IN-1] (constant indices below)
    if ((void *)(p + N_IN) > data_end) return XDP_PASS;
    long long iv0 = (long long)p[0];
    long long iv1 = (long long)p[1];
    long long iv2 = (long long)p[2];
    long long iv3 = (long long)p[3];
    long long iv4 = (long long)p[4];
    long long iv5 = (long long)p[5];
    long long iv6 = (long long)p[6];
    long long iv7 = (long long)p[7];
    long long iv8 = (long long)p[8];
    long long iv9 = (long long)p[9];
    long long iv10 = (long long)p[10];
    long long iv11 = (long long)p[11];
    long long iv12 = (long long)p[12];
    long long iv13 = (long long)p[13];
    long long iv14 = (long long)p[14];
    long long iv15 = (long long)p[15];
    long long iv16 = (long long)p[16];
    long long iv17 = (long long)p[17];
    long long iv18 = (long long)p[18];
    long long iv19 = (long long)p[19];
    long long iv20 = (long long)p[20];
    long long iv21 = (long long)p[21];
    long long iv22 = (long long)p[22];
    long long iv23 = (long long)p[23];
    long long iv24 = (long long)p[24];
    long long iv25 = (long long)p[25];
    long long iv26 = (long long)p[26];
    long long iv27 = (long long)p[27];
    long long iv28 = (long long)p[28];
    long long iv29 = (long long)p[29];
    long long iv30 = (long long)p[30];
    long long iv31 = (long long)p[31];
    long long iv32 = (long long)p[32];
    long long iv33 = (long long)p[33];
    long long iv34 = (long long)p[34];
    long long iv35 = (long long)p[35];
    long long iv36 = (long long)p[36];
    long long iv37 = (long long)p[37];
    long long iv38 = (long long)p[38];
    long long iv39 = (long long)p[39];
    long long iv40 = (long long)p[40];
    long long iv41 = (long long)p[41];
    long long iv42 = (long long)p[42];
    long long iv43 = (long long)p[43];
    long long iv44 = (long long)p[44];
    long long iv45 = (long long)p[45];
    long long iv46 = (long long)p[46];
    long long iv47 = (long long)p[47];
    long long iv48 = (long long)p[48];
    long long iv49 = (long long)p[49];
    long long iv50 = (long long)p[50];
    long long iv51 = (long long)p[51];
    long long iv52 = (long long)p[52];
    long long iv53 = (long long)p[53];
    long long iv54 = (long long)p[54];
    long long iv55 = (long long)p[55];
    long long iv56 = (long long)p[56];
    long long iv57 = (long long)p[57];
    long long iv58 = (long long)p[58];
    long long iv59 = (long long)p[59];
    long long iv60 = (long long)p[60];
    long long iv61 = (long long)p[61];
    long long iv62 = (long long)p[62];
    long long iv63 = (long long)p[63];
    long long iv64 = (long long)p[64];

    long long a1_0 = iv0 * 8LL + iv1 * 7LL + iv2 * 33LL + iv3 * -11LL + iv4 * 38LL + iv5 * 1LL + iv6 * -1LL + iv7 * -9LL + iv8 * -1LL + iv9 * -2LL + iv10 * -11LL + iv11 * 27LL + iv12 * 11LL + iv13 * 27LL + iv14 * 12LL + iv15 * 8LL + iv16 * -3LL + iv17 * 6LL + iv18 * 18LL + iv19 * 12LL + iv20 * -3LL + iv21 * -4LL + iv22 * 7LL + iv23 * 0LL + iv24 * -2LL + iv25 * 0LL + iv26 * -39LL + iv27 * 14LL + iv28 * 46LL + iv29 * 7LL + iv30 * 2LL + iv31 * 14LL + iv32 * 9LL + iv33 * -4LL + iv34 * -13LL + iv35 * -53LL + iv36 * 17LL + iv37 * -39LL + iv38 * 42LL + iv39 * -4LL + iv40 * 17LL + iv41 * -26LL + iv42 * 3LL + iv43 * 9LL + iv44 * 2LL + iv45 * -19LL + iv46 * 2LL + iv47 * 27LL + iv48 * 11LL + iv49 * 0LL + iv50 * -2LL + iv51 * 7LL + iv52 * 13LL + iv53 * 2LL + iv54 * 1LL + iv55 * 15LL + iv56 * -40LL + iv57 * 22LL + iv58 * -7LL + iv59 * 8LL + iv60 * -5LL + iv61 * -33LL + iv62 * 16LL + iv63 * 0LL + iv64 * 2LL + -36LL;
    long long h1_0 = a1_0 > 0 ? a1_0 : 0;
    long long a1_1 = iv0 * 3LL + iv1 * 1LL + iv2 * 1LL + iv3 * 20LL + iv4 * 2LL + iv5 * 16LL + iv6 * 0LL + iv7 * -6LL + iv8 * 14LL + iv9 * -20LL + iv10 * -9LL + iv11 * 0LL + iv12 * 9LL + iv13 * -6LL + iv14 * -6LL + iv15 * -14LL + iv16 * -50LL + iv17 * 3LL + iv18 * -11LL + iv19 * 13LL + iv20 * -1LL + iv21 * 1LL + iv22 * 1LL + iv23 * 4LL + iv24 * 21LL + iv25 * 6LL + iv26 * -15LL + iv27 * -3LL + iv28 * 29LL + iv29 * -14LL + iv30 * 5LL + iv31 * -9LL + iv32 * -13LL + iv33 * 4LL + iv34 * -14LL + iv35 * -19LL + iv36 * 2LL + iv37 * -36LL + iv38 * 11LL + iv39 * 1LL + iv40 * 6LL + iv41 * 2LL + iv42 * 5LL + iv43 * -15LL + iv44 * -33LL + iv45 * 14LL + iv46 * 5LL + iv47 * 1LL + iv48 * -4LL + iv49 * 6LL + iv50 * 35LL + iv51 * 8LL + iv52 * 0LL + iv53 * 6LL + iv54 * -3LL + iv55 * -10LL + iv56 * -14LL + iv57 * 9LL + iv58 * 28LL + iv59 * -4LL + iv60 * 1LL + iv61 * -2LL + iv62 * 2LL + iv63 * 0LL + iv64 * 12LL + -15LL;
    long long h1_1 = a1_1 > 0 ? a1_1 : 0;
    long long a1_2 = iv0 * -16LL + iv1 * -1LL + iv2 * 28LL + iv3 * 15LL + iv4 * 3LL + iv5 * 1LL + iv6 * 9LL + iv7 * -4LL + iv8 * -6LL + iv9 * -13LL + iv10 * -3LL + iv11 * 0LL + iv12 * -5LL + iv13 * 7LL + iv14 * 9LL + iv15 * -9LL + iv16 * -31LL + iv17 * -4LL + iv18 * 9LL + iv19 * -4LL + iv20 * -20LL + iv21 * -9LL + iv22 * -11LL + iv23 * -7LL + iv24 * -5LL + iv25 * -13LL + iv26 * -1LL + iv27 * 9LL + iv28 * 46LL + iv29 * 19LL + iv30 * -14LL + iv31 * 19LL + iv32 * 18LL + iv33 * -9LL + iv34 * 27LL + iv35 * 35LL + iv36 * 15LL + iv37 * -42LL + iv38 * 4LL + iv39 * -9LL + iv40 * -8LL + iv41 * -6LL + iv42 * -9LL + iv43 * 11LL + iv44 * -27LL + iv45 * -2LL + iv46 * -15LL + iv47 * 20LL + iv48 * -7LL + iv49 * -13LL + iv50 * -10LL + iv51 * 1LL + iv52 * 8LL + iv53 * -13LL + iv54 * -7LL + iv55 * 4LL + iv56 * 8LL + iv57 * -7LL + iv58 * 9LL + iv59 * -11LL + iv60 * -10LL + iv61 * 16LL + iv62 * 13LL + iv63 * 0LL + iv64 * -6LL + 1LL;
    long long h1_2 = a1_2 > 0 ? a1_2 : 0;
    long long a1_3 = iv0 * -9LL + iv1 * 31LL + iv2 * 6LL + iv3 * -10LL + iv4 * -10LL + iv5 * 0LL + iv6 * 6LL + iv7 * -13LL + iv8 * 7LL + iv9 * 7LL + iv10 * 2LL + iv11 * 5LL + iv12 * 2LL + iv13 * 0LL + iv14 * -7LL + iv15 * 17LL + iv16 * -18LL + iv17 * 19LL + iv18 * 24LL + iv19 * 10LL + iv20 * 19LL + iv21 * 15LL + iv22 * 4LL + iv23 * 13LL + iv24 * -27LL + iv25 * 3LL + iv26 * -13LL + iv27 * -5LL + iv28 * 15LL + iv29 * 8LL + iv30 * 5LL + iv31 * 10LL + iv32 * 9LL + iv33 * 16LL + iv34 * 18LL + iv35 * 18LL + iv36 * -8LL + iv37 * -26LL + iv38 * -18LL + iv39 * 14LL + iv40 * 12LL + iv41 * -23LL + iv42 * 5LL + iv43 * 6LL + iv44 * 15LL + iv45 * -7LL + iv46 * 6LL + iv47 * -20LL + iv48 * -3LL + iv49 * 3LL + iv50 * 0LL + iv51 * -39LL + iv52 * -8LL + iv53 * 4LL + iv54 * 13LL + iv55 * 0LL + iv56 * -29LL + iv57 * 2LL + iv58 * -38LL + iv59 * 3LL + iv60 * 13LL + iv61 * -10LL + iv62 * 24LL + iv63 * 0LL + iv64 * -7LL + 12LL;
    long long h1_3 = a1_3 > 0 ? a1_3 : 0;

    long long a2_0 = h1_0 * 51LL + h1_1 * 32LL + h1_2 * 8LL + h1_3 * -70LL + 6LL;
    long long h2_0 = a2_0 > 0 ? a2_0 : 0;
    long long a2_1 = h1_0 * 122LL + h1_1 * -82LL + h1_2 * 21LL + h1_3 * 9LL + -2LL;
    long long h2_1 = a2_1 > 0 ? a2_1 : 0;
    long long a2_2 = h1_0 * 49LL + h1_1 * 46LL + h1_2 * -30LL + h1_3 * 61LL + -20LL;
    long long h2_2 = a2_2 > 0 ? a2_2 : 0;
    long long a2_3 = h1_0 * -27LL + h1_1 * 9LL + h1_2 * 96LL + h1_3 * 40LL + 12LL;
    long long h2_3 = a2_3 > 0 ? a2_3 : 0;

    long long o_0 = h2_0 * 37LL + h2_1 * -6LL + h2_2 * 54LL + h2_3 * -82LL + -22LL;
    long long o_1 = h2_0 * -70LL + h2_1 * 16LL + h2_2 * 45LL + h2_3 * 3LL + -12LL;
    long long o_2 = h2_0 * 10LL + h2_1 * 51LL + h2_2 * -49LL + h2_3 * 37LL + -57LL;
    long long o_3 = h2_0 * 45LL + h2_1 * -121LL + h2_2 * -6LL + h2_3 * 43LL + 18LL;
    long long o_4 = h2_0 * -22LL + h2_1 * 65LL + h2_2 * -47LL + h2_3 * -33LL + 75LL;
    long long o_5 = h2_0 * 9LL + h2_1 * -8LL + h2_2 * 8LL + h2_3 * 27LL + 18LL;
    long long o_6 = h2_0 * -5LL + h2_1 * -5LL + h2_2 * -4LL + h2_3 * -13LL + -18LL;

    long long best_val = o_0; int best_cls = 0;
    if (o_1 > best_val) { best_val = o_1; best_cls = 1; }
    if (o_2 > best_val) { best_val = o_2; best_cls = 2; }
    if (o_3 > best_val) { best_val = o_3; best_cls = 3; }
    if (o_4 > best_val) { best_val = o_4; best_cls = 4; }
    if (o_5 > best_val) { best_val = o_5; best_cls = 5; }
    if (o_6 > best_val) { best_val = o_6; best_cls = 6; }
    return best_cls;   // proxy: we only load/verify, never attach
}

char _license[] SEC("license") = "GPL";
