// AUTO-GENERATED by gen_nn_c.py -- do not edit by hand.
// PoC: rodata (frozen, injected at load) weights (65-4-4-7 MLP, input read from UDP payload).
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

#define N_IN 65

// Weights live in .rodata. `const` -> .rodata section; `volatile`
// stops clang assuming the zero-initializer (the loader overwrites
// these before load via bpf_map__set_initial_value, then libbpf
// freezes the map read-only so the verifier treats them as known).
const volatile signed char W[319];

SEC("xdp")
int xdp_nn(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    signed char *p = data;
    // single bounds check covers p[0..N_IN-1] (constant indices below)
    if ((void *)(p + N_IN) > data_end) return XDP_PASS;
    long long iv0 = (long long)p[0];
    long long iv1 = (long long)p[1];
    long long iv2 = (long long)p[2];
    long long iv3 = (long long)p[3];
    long long iv4 = (long long)p[4];
    long long iv5 = (long long)p[5];
    long long iv6 = (long long)p[6];
    long long iv7 = (long long)p[7];
    long long iv8 = (long long)p[8];
    long long iv9 = (long long)p[9];
    long long iv10 = (long long)p[10];
    long long iv11 = (long long)p[11];
    long long iv12 = (long long)p[12];
    long long iv13 = (long long)p[13];
    long long iv14 = (long long)p[14];
    long long iv15 = (long long)p[15];
    long long iv16 = (long long)p[16];
    long long iv17 = (long long)p[17];
    long long iv18 = (long long)p[18];
    long long iv19 = (long long)p[19];
    long long iv20 = (long long)p[20];
    long long iv21 = (long long)p[21];
    long long iv22 = (long long)p[22];
    long long iv23 = (long long)p[23];
    long long iv24 = (long long)p[24];
    long long iv25 = (long long)p[25];
    long long iv26 = (long long)p[26];
    long long iv27 = (long long)p[27];
    long long iv28 = (long long)p[28];
    long long iv29 = (long long)p[29];
    long long iv30 = (long long)p[30];
    long long iv31 = (long long)p[31];
    long long iv32 = (long long)p[32];
    long long iv33 = (long long)p[33];
    long long iv34 = (long long)p[34];
    long long iv35 = (long long)p[35];
    long long iv36 = (long long)p[36];
    long long iv37 = (long long)p[37];
    long long iv38 = (long long)p[38];
    long long iv39 = (long long)p[39];
    long long iv40 = (long long)p[40];
    long long iv41 = (long long)p[41];
    long long iv42 = (long long)p[42];
    long long iv43 = (long long)p[43];
    long long iv44 = (long long)p[44];
    long long iv45 = (long long)p[45];
    long long iv46 = (long long)p[46];
    long long iv47 = (long long)p[47];
    long long iv48 = (long long)p[48];
    long long iv49 = (long long)p[49];
    long long iv50 = (long long)p[50];
    long long iv51 = (long long)p[51];
    long long iv52 = (long long)p[52];
    long long iv53 = (long long)p[53];
    long long iv54 = (long long)p[54];
    long long iv55 = (long long)p[55];
    long long iv56 = (long long)p[56];
    long long iv57 = (long long)p[57];
    long long iv58 = (long long)p[58];
    long long iv59 = (long long)p[59];
    long long iv60 = (long long)p[60];
    long long iv61 = (long long)p[61];
    long long iv62 = (long long)p[62];
    long long iv63 = (long long)p[63];
    long long iv64 = (long long)p[64];

    long long a1_0 = iv0 * ((long long)W[0]) + iv1 * ((long long)W[1]) + iv2 * ((long long)W[2]) + iv3 * ((long long)W[3]) + iv4 * ((long long)W[4]) + iv5 * ((long long)W[5]) + iv6 * ((long long)W[6]) + iv7 * ((long long)W[7]) + iv8 * ((long long)W[8]) + iv9 * ((long long)W[9]) + iv10 * ((long long)W[10]) + iv11 * ((long long)W[11]) + iv12 * ((long long)W[12]) + iv13 * ((long long)W[13]) + iv14 * ((long long)W[14]) + iv15 * ((long long)W[15]) + iv16 * ((long long)W[16]) + iv17 * ((long long)W[17]) + iv18 * ((long long)W[18]) + iv19 * ((long long)W[19]) + iv20 * ((long long)W[20]) + iv21 * ((long long)W[21]) + iv22 * ((long long)W[22]) + iv23 * ((long long)W[23]) + iv24 * ((long long)W[24]) + iv25 * ((long long)W[25]) + iv26 * ((long long)W[26]) + iv27 * ((long long)W[27]) + iv28 * ((long long)W[28]) + iv29 * ((long long)W[29]) + iv30 * ((long long)W[30]) + iv31 * ((long long)W[31]) + iv32 * ((long long)W[32]) + iv33 * ((long long)W[33]) + iv34 * ((long long)W[34]) + iv35 * ((long long)W[35]) + iv36 * ((long long)W[36]) + iv37 * ((long long)W[37]) + iv38 * ((long long)W[38]) + iv39 * ((long long)W[39]) + iv40 * ((long long)W[40]) + iv41 * ((long long)W[41]) + iv42 * ((long long)W[42]) + iv43 * ((long long)W[43]) + iv44 * ((long long)W[44]) + iv45 * ((long long)W[45]) + iv46 * ((long long)W[46]) + iv47 * ((long long)W[47]) + iv48 * ((long long)W[48]) + iv49 * ((long long)W[49]) + iv50 * ((long long)W[50]) + iv51 * ((long long)W[51]) + iv52 * ((long long)W[52]) + iv53 * ((long long)W[53]) + iv54 * ((long long)W[54]) + iv55 * ((long long)W[55]) + iv56 * ((long long)W[56]) + iv57 * ((long long)W[57]) + iv58 * ((long long)W[58]) + iv59 * ((long long)W[59]) + iv60 * ((long long)W[60]) + iv61 * ((long long)W[61]) + iv62 * ((long long)W[62]) + iv63 * ((long long)W[63]) + iv64 * ((long long)W[64]) + ((long long)W[260]);
    long long h1_0 = a1_0 > 0 ? a1_0 : 0;
    long long a1_1 = iv0 * ((long long)W[65]) + iv1 * ((long long)W[66]) + iv2 * ((long long)W[67]) + iv3 * ((long long)W[68]) + iv4 * ((long long)W[69]) + iv5 * ((long long)W[70]) + iv6 * ((long long)W[71]) + iv7 * ((long long)W[72]) + iv8 * ((long long)W[73]) + iv9 * ((long long)W[74]) + iv10 * ((long long)W[75]) + iv11 * ((long long)W[76]) + iv12 * ((long long)W[77]) + iv13 * ((long long)W[78]) + iv14 * ((long long)W[79]) + iv15 * ((long long)W[80]) + iv16 * ((long long)W[81]) + iv17 * ((long long)W[82]) + iv18 * ((long long)W[83]) + iv19 * ((long long)W[84]) + iv20 * ((long long)W[85]) + iv21 * ((long long)W[86]) + iv22 * ((long long)W[87]) + iv23 * ((long long)W[88]) + iv24 * ((long long)W[89]) + iv25 * ((long long)W[90]) + iv26 * ((long long)W[91]) + iv27 * ((long long)W[92]) + iv28 * ((long long)W[93]) + iv29 * ((long long)W[94]) + iv30 * ((long long)W[95]) + iv31 * ((long long)W[96]) + iv32 * ((long long)W[97]) + iv33 * ((long long)W[98]) + iv34 * ((long long)W[99]) + iv35 * ((long long)W[100]) + iv36 * ((long long)W[101]) + iv37 * ((long long)W[102]) + iv38 * ((long long)W[103]) + iv39 * ((long long)W[104]) + iv40 * ((long long)W[105]) + iv41 * ((long long)W[106]) + iv42 * ((long long)W[107]) + iv43 * ((long long)W[108]) + iv44 * ((long long)W[109]) + iv45 * ((long long)W[110]) + iv46 * ((long long)W[111]) + iv47 * ((long long)W[112]) + iv48 * ((long long)W[113]) + iv49 * ((long long)W[114]) + iv50 * ((long long)W[115]) + iv51 * ((long long)W[116]) + iv52 * ((long long)W[117]) + iv53 * ((long long)W[118]) + iv54 * ((long long)W[119]) + iv55 * ((long long)W[120]) + iv56 * ((long long)W[121]) + iv57 * ((long long)W[122]) + iv58 * ((long long)W[123]) + iv59 * ((long long)W[124]) + iv60 * ((long long)W[125]) + iv61 * ((long long)W[126]) + iv62 * ((long long)W[127]) + iv63 * ((long long)W[128]) + iv64 * ((long long)W[129]) + ((long long)W[261]);
    long long h1_1 = a1_1 > 0 ? a1_1 : 0;
    long long a1_2 = iv0 * ((long long)W[130]) + iv1 * ((long long)W[131]) + iv2 * ((long long)W[132]) + iv3 * ((long long)W[133]) + iv4 * ((long long)W[134]) + iv5 * ((long long)W[135]) + iv6 * ((long long)W[136]) + iv7 * ((long long)W[137]) + iv8 * ((long long)W[138]) + iv9 * ((long long)W[139]) + iv10 * ((long long)W[140]) + iv11 * ((long long)W[141]) + iv12 * ((long long)W[142]) + iv13 * ((long long)W[143]) + iv14 * ((long long)W[144]) + iv15 * ((long long)W[145]) + iv16 * ((long long)W[146]) + iv17 * ((long long)W[147]) + iv18 * ((long long)W[148]) + iv19 * ((long long)W[149]) + iv20 * ((long long)W[150]) + iv21 * ((long long)W[151]) + iv22 * ((long long)W[152]) + iv23 * ((long long)W[153]) + iv24 * ((long long)W[154]) + iv25 * ((long long)W[155]) + iv26 * ((long long)W[156]) + iv27 * ((long long)W[157]) + iv28 * ((long long)W[158]) + iv29 * ((long long)W[159]) + iv30 * ((long long)W[160]) + iv31 * ((long long)W[161]) + iv32 * ((long long)W[162]) + iv33 * ((long long)W[163]) + iv34 * ((long long)W[164]) + iv35 * ((long long)W[165]) + iv36 * ((long long)W[166]) + iv37 * ((long long)W[167]) + iv38 * ((long long)W[168]) + iv39 * ((long long)W[169]) + iv40 * ((long long)W[170]) + iv41 * ((long long)W[171]) + iv42 * ((long long)W[172]) + iv43 * ((long long)W[173]) + iv44 * ((long long)W[174]) + iv45 * ((long long)W[175]) + iv46 * ((long long)W[176]) + iv47 * ((long long)W[177]) + iv48 * ((long long)W[178]) + iv49 * ((long long)W[179]) + iv50 * ((long long)W[180]) + iv51 * ((long long)W[181]) + iv52 * ((long long)W[182]) + iv53 * ((long long)W[183]) + iv54 * ((long long)W[184]) + iv55 * ((long long)W[185]) + iv56 * ((long long)W[186]) + iv57 * ((long long)W[187]) + iv58 * ((long long)W[188]) + iv59 * ((long long)W[189]) + iv60 * ((long long)W[190]) + iv61 * ((long long)W[191]) + iv62 * ((long long)W[192]) + iv63 * ((long long)W[193]) + iv64 * ((long long)W[194]) + ((long long)W[262]);
    long long h1_2 = a1_2 > 0 ? a1_2 : 0;
    long long a1_3 = iv0 * ((long long)W[195]) + iv1 * ((long long)W[196]) + iv2 * ((long long)W[197]) + iv3 * ((long long)W[198]) + iv4 * ((long long)W[199]) + iv5 * ((long long)W[200]) + iv6 * ((long long)W[201]) + iv7 * ((long long)W[202]) + iv8 * ((long long)W[203]) + iv9 * ((long long)W[204]) + iv10 * ((long long)W[205]) + iv11 * ((long long)W[206]) + iv12 * ((long long)W[207]) + iv13 * ((long long)W[208]) + iv14 * ((long long)W[209]) + iv15 * ((long long)W[210]) + iv16 * ((long long)W[211]) + iv17 * ((long long)W[212]) + iv18 * ((long long)W[213]) + iv19 * ((long long)W[214]) + iv20 * ((long long)W[215]) + iv21 * ((long long)W[216]) + iv22 * ((long long)W[217]) + iv23 * ((long long)W[218]) + iv24 * ((long long)W[219]) + iv25 * ((long long)W[220]) + iv26 * ((long long)W[221]) + iv27 * ((long long)W[222]) + iv28 * ((long long)W[223]) + iv29 * ((long long)W[224]) + iv30 * ((long long)W[225]) + iv31 * ((long long)W[226]) + iv32 * ((long long)W[227]) + iv33 * ((long long)W[228]) + iv34 * ((long long)W[229]) + iv35 * ((long long)W[230]) + iv36 * ((long long)W[231]) + iv37 * ((long long)W[232]) + iv38 * ((long long)W[233]) + iv39 * ((long long)W[234]) + iv40 * ((long long)W[235]) + iv41 * ((long long)W[236]) + iv42 * ((long long)W[237]) + iv43 * ((long long)W[238]) + iv44 * ((long long)W[239]) + iv45 * ((long long)W[240]) + iv46 * ((long long)W[241]) + iv47 * ((long long)W[242]) + iv48 * ((long long)W[243]) + iv49 * ((long long)W[244]) + iv50 * ((long long)W[245]) + iv51 * ((long long)W[246]) + iv52 * ((long long)W[247]) + iv53 * ((long long)W[248]) + iv54 * ((long long)W[249]) + iv55 * ((long long)W[250]) + iv56 * ((long long)W[251]) + iv57 * ((long long)W[252]) + iv58 * ((long long)W[253]) + iv59 * ((long long)W[254]) + iv60 * ((long long)W[255]) + iv61 * ((long long)W[256]) + iv62 * ((long long)W[257]) + iv63 * ((long long)W[258]) + iv64 * ((long long)W[259]) + ((long long)W[263]);
    long long h1_3 = a1_3 > 0 ? a1_3 : 0;

    long long a2_0 = h1_0 * ((long long)W[264]) + h1_1 * ((long long)W[265]) + h1_2 * ((long long)W[266]) + h1_3 * ((long long)W[267]) + ((long long)W[280]);
    long long h2_0 = a2_0 > 0 ? a2_0 : 0;
    long long a2_1 = h1_0 * ((long long)W[268]) + h1_1 * ((long long)W[269]) + h1_2 * ((long long)W[270]) + h1_3 * ((long long)W[271]) + ((long long)W[281]);
    long long h2_1 = a2_1 > 0 ? a2_1 : 0;
    long long a2_2 = h1_0 * ((long long)W[272]) + h1_1 * ((long long)W[273]) + h1_2 * ((long long)W[274]) + h1_3 * ((long long)W[275]) + ((long long)W[282]);
    long long h2_2 = a2_2 > 0 ? a2_2 : 0;
    long long a2_3 = h1_0 * ((long long)W[276]) + h1_1 * ((long long)W[277]) + h1_2 * ((long long)W[278]) + h1_3 * ((long long)W[279]) + ((long long)W[283]);
    long long h2_3 = a2_3 > 0 ? a2_3 : 0;

    long long o_0 = h2_0 * ((long long)W[284]) + h2_1 * ((long long)W[285]) + h2_2 * ((long long)W[286]) + h2_3 * ((long long)W[287]) + ((long long)W[312]);
    long long o_1 = h2_0 * ((long long)W[288]) + h2_1 * ((long long)W[289]) + h2_2 * ((long long)W[290]) + h2_3 * ((long long)W[291]) + ((long long)W[313]);
    long long o_2 = h2_0 * ((long long)W[292]) + h2_1 * ((long long)W[293]) + h2_2 * ((long long)W[294]) + h2_3 * ((long long)W[295]) + ((long long)W[314]);
    long long o_3 = h2_0 * ((long long)W[296]) + h2_1 * ((long long)W[297]) + h2_2 * ((long long)W[298]) + h2_3 * ((long long)W[299]) + ((long long)W[315]);
    long long o_4 = h2_0 * ((long long)W[300]) + h2_1 * ((long long)W[301]) + h2_2 * ((long long)W[302]) + h2_3 * ((long long)W[303]) + ((long long)W[316]);
    long long o_5 = h2_0 * ((long long)W[304]) + h2_1 * ((long long)W[305]) + h2_2 * ((long long)W[306]) + h2_3 * ((long long)W[307]) + ((long long)W[317]);
    long long o_6 = h2_0 * ((long long)W[308]) + h2_1 * ((long long)W[309]) + h2_2 * ((long long)W[310]) + h2_3 * ((long long)W[311]) + ((long long)W[318]);

    long long best_val = o_0; int best_cls = 0;
    if (o_1 > best_val) { best_val = o_1; best_cls = 1; }
    if (o_2 > best_val) { best_val = o_2; best_cls = 2; }
    if (o_3 > best_val) { best_val = o_3; best_cls = 3; }
    if (o_4 > best_val) { best_val = o_4; best_cls = 4; }
    if (o_5 > best_val) { best_val = o_5; best_cls = 5; }
    if (o_6 > best_val) { best_val = o_6; best_cls = 6; }
    return best_cls;   // proxy: we only load/verify, never attach
}

char _license[] SEC("license") = "GPL";
