// AUTO-GENERATED by gen_sparse_c.py -- do not edit by hand.
// PoC: literal (baked) weights, SPARSE structure (one-hot switches, 6 dense link_state).
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

SEC("xdp")
int xdp_nn_sparse(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    signed char *p = data;
    if ((void *)(p + 9) > data_end) return XDP_PASS;
    // input sources (payload stands in for link_state map / ttl / ctx):
    long long ls0=(long long)p[0], ls1=(long long)p[1], ls2=(long long)p[2];
    long long ls3=(long long)p[3], ls4=(long long)p[4], ls5=(long long)p[5];
    long long ttl=(long long)p[6];
    int iface_idx = (int)p[7];   // logical ingress port 1..6 (0 = none)
    int node_idx  = (int)p[8];   // node one-hot index 0..51

    // ingress_iface one-hot: one switch picks one weight per neuron
    long long w_iface_0 = 0;
    long long w_iface_1 = 0;
    long long w_iface_2 = 0;
    long long w_iface_3 = 0;
    switch (iface_idx) {
        case 1: w_iface_0 = -1LL; w_iface_1 = 0LL; w_iface_2 = 9LL; w_iface_3 = 6LL; break;
        case 2: w_iface_0 = -9LL; w_iface_1 = -6LL; w_iface_2 = -4LL; w_iface_3 = -13LL; break;
        case 3: w_iface_0 = -1LL; w_iface_1 = 14LL; w_iface_2 = -6LL; w_iface_3 = 7LL; break;
        case 4: w_iface_0 = -2LL; w_iface_1 = -20LL; w_iface_2 = -13LL; w_iface_3 = 7LL; break;
        case 5: w_iface_0 = -11LL; w_iface_1 = -9LL; w_iface_2 = -3LL; w_iface_3 = 2LL; break;
        case 6: w_iface_0 = 27LL; w_iface_1 = 0LL; w_iface_2 = 0LL; w_iface_3 = 5LL; break;
        default: break;
    }
    // node one-hot: one switch picks one weight per neuron
    long long w_node_0 = 0;
    long long w_node_1 = 0;
    long long w_node_2 = 0;
    long long w_node_3 = 0;
    switch (node_idx) {
        case 0: w_node_0 = 27LL; w_node_1 = -6LL; w_node_2 = 7LL; w_node_3 = 0LL; break;
        case 1: w_node_0 = 12LL; w_node_1 = -6LL; w_node_2 = 9LL; w_node_3 = -7LL; break;
        case 2: w_node_0 = 8LL; w_node_1 = -14LL; w_node_2 = -9LL; w_node_3 = 17LL; break;
        case 3: w_node_0 = -3LL; w_node_1 = -50LL; w_node_2 = -31LL; w_node_3 = -18LL; break;
        case 4: w_node_0 = 6LL; w_node_1 = 3LL; w_node_2 = -4LL; w_node_3 = 19LL; break;
        case 5: w_node_0 = 18LL; w_node_1 = -11LL; w_node_2 = 9LL; w_node_3 = 24LL; break;
        case 6: w_node_0 = 12LL; w_node_1 = 13LL; w_node_2 = -4LL; w_node_3 = 10LL; break;
        case 7: w_node_0 = -3LL; w_node_1 = -1LL; w_node_2 = -20LL; w_node_3 = 19LL; break;
        case 8: w_node_0 = -4LL; w_node_1 = 1LL; w_node_2 = -9LL; w_node_3 = 15LL; break;
        case 9: w_node_0 = 7LL; w_node_1 = 1LL; w_node_2 = -11LL; w_node_3 = 4LL; break;
        case 10: w_node_0 = 0LL; w_node_1 = 4LL; w_node_2 = -7LL; w_node_3 = 13LL; break;
        case 11: w_node_0 = -2LL; w_node_1 = 21LL; w_node_2 = -5LL; w_node_3 = -27LL; break;
        case 12: w_node_0 = 0LL; w_node_1 = 6LL; w_node_2 = -13LL; w_node_3 = 3LL; break;
        case 13: w_node_0 = -39LL; w_node_1 = -15LL; w_node_2 = -1LL; w_node_3 = -13LL; break;
        case 14: w_node_0 = 14LL; w_node_1 = -3LL; w_node_2 = 9LL; w_node_3 = -5LL; break;
        case 15: w_node_0 = 46LL; w_node_1 = 29LL; w_node_2 = 46LL; w_node_3 = 15LL; break;
        case 16: w_node_0 = 7LL; w_node_1 = -14LL; w_node_2 = 19LL; w_node_3 = 8LL; break;
        case 17: w_node_0 = 2LL; w_node_1 = 5LL; w_node_2 = -14LL; w_node_3 = 5LL; break;
        case 18: w_node_0 = 14LL; w_node_1 = -9LL; w_node_2 = 19LL; w_node_3 = 10LL; break;
        case 19: w_node_0 = 9LL; w_node_1 = -13LL; w_node_2 = 18LL; w_node_3 = 9LL; break;
        case 20: w_node_0 = -4LL; w_node_1 = 4LL; w_node_2 = -9LL; w_node_3 = 16LL; break;
        case 21: w_node_0 = -13LL; w_node_1 = -14LL; w_node_2 = 27LL; w_node_3 = 18LL; break;
        case 22: w_node_0 = -53LL; w_node_1 = -19LL; w_node_2 = 35LL; w_node_3 = 18LL; break;
        case 23: w_node_0 = 17LL; w_node_1 = 2LL; w_node_2 = 15LL; w_node_3 = -8LL; break;
        case 24: w_node_0 = -39LL; w_node_1 = -36LL; w_node_2 = -42LL; w_node_3 = -26LL; break;
        case 25: w_node_0 = 42LL; w_node_1 = 11LL; w_node_2 = 4LL; w_node_3 = -18LL; break;
        case 26: w_node_0 = -4LL; w_node_1 = 1LL; w_node_2 = -9LL; w_node_3 = 14LL; break;
        case 27: w_node_0 = 17LL; w_node_1 = 6LL; w_node_2 = -8LL; w_node_3 = 12LL; break;
        case 28: w_node_0 = -26LL; w_node_1 = 2LL; w_node_2 = -6LL; w_node_3 = -23LL; break;
        case 29: w_node_0 = 3LL; w_node_1 = 5LL; w_node_2 = -9LL; w_node_3 = 5LL; break;
        case 30: w_node_0 = 9LL; w_node_1 = -15LL; w_node_2 = 11LL; w_node_3 = 6LL; break;
        case 31: w_node_0 = 2LL; w_node_1 = -33LL; w_node_2 = -27LL; w_node_3 = 15LL; break;
        case 32: w_node_0 = -19LL; w_node_1 = 14LL; w_node_2 = -2LL; w_node_3 = -7LL; break;
        case 33: w_node_0 = 2LL; w_node_1 = 5LL; w_node_2 = -15LL; w_node_3 = 6LL; break;
        case 34: w_node_0 = 27LL; w_node_1 = 1LL; w_node_2 = 20LL; w_node_3 = -20LL; break;
        case 35: w_node_0 = 11LL; w_node_1 = -4LL; w_node_2 = -7LL; w_node_3 = -3LL; break;
        case 36: w_node_0 = 0LL; w_node_1 = 6LL; w_node_2 = -13LL; w_node_3 = 3LL; break;
        case 37: w_node_0 = -2LL; w_node_1 = 35LL; w_node_2 = -10LL; w_node_3 = 0LL; break;
        case 38: w_node_0 = 7LL; w_node_1 = 8LL; w_node_2 = 1LL; w_node_3 = -39LL; break;
        case 39: w_node_0 = 13LL; w_node_1 = 0LL; w_node_2 = 8LL; w_node_3 = -8LL; break;
        case 40: w_node_0 = 2LL; w_node_1 = 6LL; w_node_2 = -13LL; w_node_3 = 4LL; break;
        case 41: w_node_0 = 1LL; w_node_1 = -3LL; w_node_2 = -7LL; w_node_3 = 13LL; break;
        case 42: w_node_0 = 15LL; w_node_1 = -10LL; w_node_2 = 4LL; w_node_3 = 0LL; break;
        case 43: w_node_0 = -40LL; w_node_1 = -14LL; w_node_2 = 8LL; w_node_3 = -29LL; break;
        case 44: w_node_0 = 22LL; w_node_1 = 9LL; w_node_2 = -7LL; w_node_3 = 2LL; break;
        case 45: w_node_0 = -7LL; w_node_1 = 28LL; w_node_2 = 9LL; w_node_3 = -38LL; break;
        case 46: w_node_0 = 8LL; w_node_1 = -4LL; w_node_2 = -11LL; w_node_3 = 3LL; break;
        case 47: w_node_0 = -5LL; w_node_1 = 1LL; w_node_2 = -10LL; w_node_3 = 13LL; break;
        case 48: w_node_0 = -33LL; w_node_1 = -2LL; w_node_2 = 16LL; w_node_3 = -10LL; break;
        case 49: w_node_0 = 16LL; w_node_1 = 2LL; w_node_2 = 13LL; w_node_3 = 24LL; break;
        case 50: w_node_0 = 0LL; w_node_1 = 0LL; w_node_2 = 0LL; w_node_3 = 0LL; break;
        case 51: w_node_0 = 2LL; w_node_1 = 12LL; w_node_2 = -6LL; w_node_3 = -7LL; break;
        default: break;
    }

    long long a1_0 = ls0 * 8LL + ls1 * 7LL + ls2 * 33LL + ls3 * -11LL + ls4 * 38LL + ls5 * 1LL + ttl * 11LL + w_iface_0 + w_node_0 + -36LL;
    long long h1_0 = a1_0 > 0 ? a1_0 : 0;
    long long a1_1 = ls0 * 3LL + ls1 * 1LL + ls2 * 1LL + ls3 * 20LL + ls4 * 2LL + ls5 * 16LL + ttl * 9LL + w_iface_1 + w_node_1 + -15LL;
    long long h1_1 = a1_1 > 0 ? a1_1 : 0;
    long long a1_2 = ls0 * -16LL + ls1 * -1LL + ls2 * 28LL + ls3 * 15LL + ls4 * 3LL + ls5 * 1LL + ttl * -5LL + w_iface_2 + w_node_2 + 1LL;
    long long h1_2 = a1_2 > 0 ? a1_2 : 0;
    long long a1_3 = ls0 * -9LL + ls1 * 31LL + ls2 * 6LL + ls3 * -10LL + ls4 * -10LL + ls5 * 0LL + ttl * 2LL + w_iface_3 + w_node_3 + 12LL;
    long long h1_3 = a1_3 > 0 ? a1_3 : 0;

    long long a2_0 = h1_0 * 51LL + h1_1 * 32LL + h1_2 * 8LL + h1_3 * -70LL + 6LL;
    long long h2_0 = a2_0 > 0 ? a2_0 : 0;
    long long a2_1 = h1_0 * 122LL + h1_1 * -82LL + h1_2 * 21LL + h1_3 * 9LL + -2LL;
    long long h2_1 = a2_1 > 0 ? a2_1 : 0;
    long long a2_2 = h1_0 * 49LL + h1_1 * 46LL + h1_2 * -30LL + h1_3 * 61LL + -20LL;
    long long h2_2 = a2_2 > 0 ? a2_2 : 0;
    long long a2_3 = h1_0 * -27LL + h1_1 * 9LL + h1_2 * 96LL + h1_3 * 40LL + 12LL;
    long long h2_3 = a2_3 > 0 ? a2_3 : 0;

    long long o_0 = h2_0 * 37LL + h2_1 * -6LL + h2_2 * 54LL + h2_3 * -82LL + -22LL;
    long long o_1 = h2_0 * -70LL + h2_1 * 16LL + h2_2 * 45LL + h2_3 * 3LL + -12LL;
    long long o_2 = h2_0 * 10LL + h2_1 * 51LL + h2_2 * -49LL + h2_3 * 37LL + -57LL;
    long long o_3 = h2_0 * 45LL + h2_1 * -121LL + h2_2 * -6LL + h2_3 * 43LL + 18LL;
    long long o_4 = h2_0 * -22LL + h2_1 * 65LL + h2_2 * -47LL + h2_3 * -33LL + 75LL;
    long long o_5 = h2_0 * 9LL + h2_1 * -8LL + h2_2 * 8LL + h2_3 * 27LL + 18LL;
    long long o_6 = h2_0 * -5LL + h2_1 * -5LL + h2_2 * -4LL + h2_3 * -13LL + -18LL;

    long long best_val = o_0; int best_cls = 0;
    if (o_1 > best_val) { best_val = o_1; best_cls = 1; }
    if (o_2 > best_val) { best_val = o_2; best_cls = 2; }
    if (o_3 > best_val) { best_val = o_3; best_cls = 3; }
    if (o_4 > best_val) { best_val = o_4; best_cls = 4; }
    if (o_5 > best_val) { best_val = o_5; best_cls = 5; }
    if (o_6 > best_val) { best_val = o_6; best_cls = 6; }
    return best_cls;
}

char _license[] SEC("license") = "GPL";
