// AUTO-GENERATED by gen_sparse_c.py -- do not edit by hand.
// PoC: rodata (frozen, injected) weights, SPARSE structure (one-hot switches, 6 dense link_state).
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

// Weights in .rodata (loader injects real values before load, libbpf
// freezes it read-only). One-hot features read ONE W[] per neuron per
// packet via the switch below -- same access pattern as the literal
// build's per-case immediate, but a load instead of an immediate.
const volatile signed char W[319];

SEC("xdp")
int xdp_nn_sparse(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;
    signed char *p = data;
    if ((void *)(p + 9) > data_end) return XDP_PASS;
    // input sources (payload stands in for link_state map / ttl / ctx):
    long long ls0=(long long)p[0], ls1=(long long)p[1], ls2=(long long)p[2];
    long long ls3=(long long)p[3], ls4=(long long)p[4], ls5=(long long)p[5];
    long long ttl=(long long)p[6];
    int iface_idx = (int)p[7];   // logical ingress port 1..6 (0 = none)
    int node_idx  = (int)p[8];   // node one-hot index 0..51

    // ingress_iface one-hot: one switch picks one weight per neuron
    long long w_iface_0 = 0;
    long long w_iface_1 = 0;
    long long w_iface_2 = 0;
    long long w_iface_3 = 0;
    switch (iface_idx) {
        case 1: w_iface_0 = ((long long)W[6]); w_iface_1 = ((long long)W[71]); w_iface_2 = ((long long)W[136]); w_iface_3 = ((long long)W[201]); break;
        case 2: w_iface_0 = ((long long)W[7]); w_iface_1 = ((long long)W[72]); w_iface_2 = ((long long)W[137]); w_iface_3 = ((long long)W[202]); break;
        case 3: w_iface_0 = ((long long)W[8]); w_iface_1 = ((long long)W[73]); w_iface_2 = ((long long)W[138]); w_iface_3 = ((long long)W[203]); break;
        case 4: w_iface_0 = ((long long)W[9]); w_iface_1 = ((long long)W[74]); w_iface_2 = ((long long)W[139]); w_iface_3 = ((long long)W[204]); break;
        case 5: w_iface_0 = ((long long)W[10]); w_iface_1 = ((long long)W[75]); w_iface_2 = ((long long)W[140]); w_iface_3 = ((long long)W[205]); break;
        case 6: w_iface_0 = ((long long)W[11]); w_iface_1 = ((long long)W[76]); w_iface_2 = ((long long)W[141]); w_iface_3 = ((long long)W[206]); break;
        default: break;
    }
    // node one-hot: one switch picks one weight per neuron
    long long w_node_0 = 0;
    long long w_node_1 = 0;
    long long w_node_2 = 0;
    long long w_node_3 = 0;
    switch (node_idx) {
        case 0: w_node_0 = ((long long)W[13]); w_node_1 = ((long long)W[78]); w_node_2 = ((long long)W[143]); w_node_3 = ((long long)W[208]); break;
        case 1: w_node_0 = ((long long)W[14]); w_node_1 = ((long long)W[79]); w_node_2 = ((long long)W[144]); w_node_3 = ((long long)W[209]); break;
        case 2: w_node_0 = ((long long)W[15]); w_node_1 = ((long long)W[80]); w_node_2 = ((long long)W[145]); w_node_3 = ((long long)W[210]); break;
        case 3: w_node_0 = ((long long)W[16]); w_node_1 = ((long long)W[81]); w_node_2 = ((long long)W[146]); w_node_3 = ((long long)W[211]); break;
        case 4: w_node_0 = ((long long)W[17]); w_node_1 = ((long long)W[82]); w_node_2 = ((long long)W[147]); w_node_3 = ((long long)W[212]); break;
        case 5: w_node_0 = ((long long)W[18]); w_node_1 = ((long long)W[83]); w_node_2 = ((long long)W[148]); w_node_3 = ((long long)W[213]); break;
        case 6: w_node_0 = ((long long)W[19]); w_node_1 = ((long long)W[84]); w_node_2 = ((long long)W[149]); w_node_3 = ((long long)W[214]); break;
        case 7: w_node_0 = ((long long)W[20]); w_node_1 = ((long long)W[85]); w_node_2 = ((long long)W[150]); w_node_3 = ((long long)W[215]); break;
        case 8: w_node_0 = ((long long)W[21]); w_node_1 = ((long long)W[86]); w_node_2 = ((long long)W[151]); w_node_3 = ((long long)W[216]); break;
        case 9: w_node_0 = ((long long)W[22]); w_node_1 = ((long long)W[87]); w_node_2 = ((long long)W[152]); w_node_3 = ((long long)W[217]); break;
        case 10: w_node_0 = ((long long)W[23]); w_node_1 = ((long long)W[88]); w_node_2 = ((long long)W[153]); w_node_3 = ((long long)W[218]); break;
        case 11: w_node_0 = ((long long)W[24]); w_node_1 = ((long long)W[89]); w_node_2 = ((long long)W[154]); w_node_3 = ((long long)W[219]); break;
        case 12: w_node_0 = ((long long)W[25]); w_node_1 = ((long long)W[90]); w_node_2 = ((long long)W[155]); w_node_3 = ((long long)W[220]); break;
        case 13: w_node_0 = ((long long)W[26]); w_node_1 = ((long long)W[91]); w_node_2 = ((long long)W[156]); w_node_3 = ((long long)W[221]); break;
        case 14: w_node_0 = ((long long)W[27]); w_node_1 = ((long long)W[92]); w_node_2 = ((long long)W[157]); w_node_3 = ((long long)W[222]); break;
        case 15: w_node_0 = ((long long)W[28]); w_node_1 = ((long long)W[93]); w_node_2 = ((long long)W[158]); w_node_3 = ((long long)W[223]); break;
        case 16: w_node_0 = ((long long)W[29]); w_node_1 = ((long long)W[94]); w_node_2 = ((long long)W[159]); w_node_3 = ((long long)W[224]); break;
        case 17: w_node_0 = ((long long)W[30]); w_node_1 = ((long long)W[95]); w_node_2 = ((long long)W[160]); w_node_3 = ((long long)W[225]); break;
        case 18: w_node_0 = ((long long)W[31]); w_node_1 = ((long long)W[96]); w_node_2 = ((long long)W[161]); w_node_3 = ((long long)W[226]); break;
        case 19: w_node_0 = ((long long)W[32]); w_node_1 = ((long long)W[97]); w_node_2 = ((long long)W[162]); w_node_3 = ((long long)W[227]); break;
        case 20: w_node_0 = ((long long)W[33]); w_node_1 = ((long long)W[98]); w_node_2 = ((long long)W[163]); w_node_3 = ((long long)W[228]); break;
        case 21: w_node_0 = ((long long)W[34]); w_node_1 = ((long long)W[99]); w_node_2 = ((long long)W[164]); w_node_3 = ((long long)W[229]); break;
        case 22: w_node_0 = ((long long)W[35]); w_node_1 = ((long long)W[100]); w_node_2 = ((long long)W[165]); w_node_3 = ((long long)W[230]); break;
        case 23: w_node_0 = ((long long)W[36]); w_node_1 = ((long long)W[101]); w_node_2 = ((long long)W[166]); w_node_3 = ((long long)W[231]); break;
        case 24: w_node_0 = ((long long)W[37]); w_node_1 = ((long long)W[102]); w_node_2 = ((long long)W[167]); w_node_3 = ((long long)W[232]); break;
        case 25: w_node_0 = ((long long)W[38]); w_node_1 = ((long long)W[103]); w_node_2 = ((long long)W[168]); w_node_3 = ((long long)W[233]); break;
        case 26: w_node_0 = ((long long)W[39]); w_node_1 = ((long long)W[104]); w_node_2 = ((long long)W[169]); w_node_3 = ((long long)W[234]); break;
        case 27: w_node_0 = ((long long)W[40]); w_node_1 = ((long long)W[105]); w_node_2 = ((long long)W[170]); w_node_3 = ((long long)W[235]); break;
        case 28: w_node_0 = ((long long)W[41]); w_node_1 = ((long long)W[106]); w_node_2 = ((long long)W[171]); w_node_3 = ((long long)W[236]); break;
        case 29: w_node_0 = ((long long)W[42]); w_node_1 = ((long long)W[107]); w_node_2 = ((long long)W[172]); w_node_3 = ((long long)W[237]); break;
        case 30: w_node_0 = ((long long)W[43]); w_node_1 = ((long long)W[108]); w_node_2 = ((long long)W[173]); w_node_3 = ((long long)W[238]); break;
        case 31: w_node_0 = ((long long)W[44]); w_node_1 = ((long long)W[109]); w_node_2 = ((long long)W[174]); w_node_3 = ((long long)W[239]); break;
        case 32: w_node_0 = ((long long)W[45]); w_node_1 = ((long long)W[110]); w_node_2 = ((long long)W[175]); w_node_3 = ((long long)W[240]); break;
        case 33: w_node_0 = ((long long)W[46]); w_node_1 = ((long long)W[111]); w_node_2 = ((long long)W[176]); w_node_3 = ((long long)W[241]); break;
        case 34: w_node_0 = ((long long)W[47]); w_node_1 = ((long long)W[112]); w_node_2 = ((long long)W[177]); w_node_3 = ((long long)W[242]); break;
        case 35: w_node_0 = ((long long)W[48]); w_node_1 = ((long long)W[113]); w_node_2 = ((long long)W[178]); w_node_3 = ((long long)W[243]); break;
        case 36: w_node_0 = ((long long)W[49]); w_node_1 = ((long long)W[114]); w_node_2 = ((long long)W[179]); w_node_3 = ((long long)W[244]); break;
        case 37: w_node_0 = ((long long)W[50]); w_node_1 = ((long long)W[115]); w_node_2 = ((long long)W[180]); w_node_3 = ((long long)W[245]); break;
        case 38: w_node_0 = ((long long)W[51]); w_node_1 = ((long long)W[116]); w_node_2 = ((long long)W[181]); w_node_3 = ((long long)W[246]); break;
        case 39: w_node_0 = ((long long)W[52]); w_node_1 = ((long long)W[117]); w_node_2 = ((long long)W[182]); w_node_3 = ((long long)W[247]); break;
        case 40: w_node_0 = ((long long)W[53]); w_node_1 = ((long long)W[118]); w_node_2 = ((long long)W[183]); w_node_3 = ((long long)W[248]); break;
        case 41: w_node_0 = ((long long)W[54]); w_node_1 = ((long long)W[119]); w_node_2 = ((long long)W[184]); w_node_3 = ((long long)W[249]); break;
        case 42: w_node_0 = ((long long)W[55]); w_node_1 = ((long long)W[120]); w_node_2 = ((long long)W[185]); w_node_3 = ((long long)W[250]); break;
        case 43: w_node_0 = ((long long)W[56]); w_node_1 = ((long long)W[121]); w_node_2 = ((long long)W[186]); w_node_3 = ((long long)W[251]); break;
        case 44: w_node_0 = ((long long)W[57]); w_node_1 = ((long long)W[122]); w_node_2 = ((long long)W[187]); w_node_3 = ((long long)W[252]); break;
        case 45: w_node_0 = ((long long)W[58]); w_node_1 = ((long long)W[123]); w_node_2 = ((long long)W[188]); w_node_3 = ((long long)W[253]); break;
        case 46: w_node_0 = ((long long)W[59]); w_node_1 = ((long long)W[124]); w_node_2 = ((long long)W[189]); w_node_3 = ((long long)W[254]); break;
        case 47: w_node_0 = ((long long)W[60]); w_node_1 = ((long long)W[125]); w_node_2 = ((long long)W[190]); w_node_3 = ((long long)W[255]); break;
        case 48: w_node_0 = ((long long)W[61]); w_node_1 = ((long long)W[126]); w_node_2 = ((long long)W[191]); w_node_3 = ((long long)W[256]); break;
        case 49: w_node_0 = ((long long)W[62]); w_node_1 = ((long long)W[127]); w_node_2 = ((long long)W[192]); w_node_3 = ((long long)W[257]); break;
        case 50: w_node_0 = ((long long)W[63]); w_node_1 = ((long long)W[128]); w_node_2 = ((long long)W[193]); w_node_3 = ((long long)W[258]); break;
        case 51: w_node_0 = ((long long)W[64]); w_node_1 = ((long long)W[129]); w_node_2 = ((long long)W[194]); w_node_3 = ((long long)W[259]); break;
        default: break;
    }

    long long a1_0 = ls0 * ((long long)W[0]) + ls1 * ((long long)W[1]) + ls2 * ((long long)W[2]) + ls3 * ((long long)W[3]) + ls4 * ((long long)W[4]) + ls5 * ((long long)W[5]) + ttl * ((long long)W[12]) + w_iface_0 + w_node_0 + ((long long)W[260]);
    long long h1_0 = a1_0 > 0 ? a1_0 : 0;
    long long a1_1 = ls0 * ((long long)W[65]) + ls1 * ((long long)W[66]) + ls2 * ((long long)W[67]) + ls3 * ((long long)W[68]) + ls4 * ((long long)W[69]) + ls5 * ((long long)W[70]) + ttl * ((long long)W[77]) + w_iface_1 + w_node_1 + ((long long)W[261]);
    long long h1_1 = a1_1 > 0 ? a1_1 : 0;
    long long a1_2 = ls0 * ((long long)W[130]) + ls1 * ((long long)W[131]) + ls2 * ((long long)W[132]) + ls3 * ((long long)W[133]) + ls4 * ((long long)W[134]) + ls5 * ((long long)W[135]) + ttl * ((long long)W[142]) + w_iface_2 + w_node_2 + ((long long)W[262]);
    long long h1_2 = a1_2 > 0 ? a1_2 : 0;
    long long a1_3 = ls0 * ((long long)W[195]) + ls1 * ((long long)W[196]) + ls2 * ((long long)W[197]) + ls3 * ((long long)W[198]) + ls4 * ((long long)W[199]) + ls5 * ((long long)W[200]) + ttl * ((long long)W[207]) + w_iface_3 + w_node_3 + ((long long)W[263]);
    long long h1_3 = a1_3 > 0 ? a1_3 : 0;

    long long a2_0 = h1_0 * ((long long)W[264]) + h1_1 * ((long long)W[265]) + h1_2 * ((long long)W[266]) + h1_3 * ((long long)W[267]) + ((long long)W[280]);
    long long h2_0 = a2_0 > 0 ? a2_0 : 0;
    long long a2_1 = h1_0 * ((long long)W[268]) + h1_1 * ((long long)W[269]) + h1_2 * ((long long)W[270]) + h1_3 * ((long long)W[271]) + ((long long)W[281]);
    long long h2_1 = a2_1 > 0 ? a2_1 : 0;
    long long a2_2 = h1_0 * ((long long)W[272]) + h1_1 * ((long long)W[273]) + h1_2 * ((long long)W[274]) + h1_3 * ((long long)W[275]) + ((long long)W[282]);
    long long h2_2 = a2_2 > 0 ? a2_2 : 0;
    long long a2_3 = h1_0 * ((long long)W[276]) + h1_1 * ((long long)W[277]) + h1_2 * ((long long)W[278]) + h1_3 * ((long long)W[279]) + ((long long)W[283]);
    long long h2_3 = a2_3 > 0 ? a2_3 : 0;

    long long o_0 = h2_0 * ((long long)W[284]) + h2_1 * ((long long)W[285]) + h2_2 * ((long long)W[286]) + h2_3 * ((long long)W[287]) + ((long long)W[312]);
    long long o_1 = h2_0 * ((long long)W[288]) + h2_1 * ((long long)W[289]) + h2_2 * ((long long)W[290]) + h2_3 * ((long long)W[291]) + ((long long)W[313]);
    long long o_2 = h2_0 * ((long long)W[292]) + h2_1 * ((long long)W[293]) + h2_2 * ((long long)W[294]) + h2_3 * ((long long)W[295]) + ((long long)W[314]);
    long long o_3 = h2_0 * ((long long)W[296]) + h2_1 * ((long long)W[297]) + h2_2 * ((long long)W[298]) + h2_3 * ((long long)W[299]) + ((long long)W[315]);
    long long o_4 = h2_0 * ((long long)W[300]) + h2_1 * ((long long)W[301]) + h2_2 * ((long long)W[302]) + h2_3 * ((long long)W[303]) + ((long long)W[316]);
    long long o_5 = h2_0 * ((long long)W[304]) + h2_1 * ((long long)W[305]) + h2_2 * ((long long)W[306]) + h2_3 * ((long long)W[307]) + ((long long)W[317]);
    long long o_6 = h2_0 * ((long long)W[308]) + h2_1 * ((long long)W[309]) + h2_2 * ((long long)W[310]) + h2_3 * ((long long)W[311]) + ((long long)W[318]);

    long long best_val = o_0; int best_cls = 0;
    if (o_1 > best_val) { best_val = o_1; best_cls = 1; }
    if (o_2 > best_val) { best_val = o_2; best_cls = 2; }
    if (o_3 > best_val) { best_val = o_3; best_cls = 3; }
    if (o_4 > best_val) { best_val = o_4; best_cls = 4; }
    if (o_5 > best_val) { best_val = o_5; best_cls = 5; }
    if (o_6 > best_val) { best_val = o_6; best_cls = 6; }
    return best_cls;
}

char _license[] SEC("license") = "GPL";
